# Loading the preprocessed datasets into the database
This notebook preforms further cleaning and grouping on the datasets to match our database schema and then inserts the data into the database along with links between the entities.

### Notes on the process
1) Dataset choice
- The datasets do intersect only in 5 animal species, thus they are not a subset of each other.

2) Cleaning and filtering
- The datasets were heavily filtered and cleaned to obtain the data that fit our purpose and defined schema.

    -> we have worked with data and dates conversion, missing values cleaning, collapsing columns into individual rows suitable for insertion...
- The preprocessing was done in separate files for each dataset also available in the repo.
- Final conversion into the desired format to match the schema and insertion was done in this file.

3) Normalisation
- We filtered and pre-processed both of the datasets in such a way that further normalisation was not needed at this point.

4) Constraint Changes
- In DB_Definition.ipynb where the schema is defined, we have deleted the DEFAUT TRUE for a BOOLEAN NATIVE attribute as we do not have any information about whether of nor the aminals we are inserting are truly native.

### Limitations

1) The datasets chosen do not contain all the information needed to populate all entities and attribues, thus, many fields remain NULL.

2) The difference between how each dataset deals with location could be addressed. Currently, we store the animal populations only on a state level as this is the information that appears in both datasets. However, the tsx dataset does monitor the species also on a basis of a region. Thus, we could make the recordings more precise, but that would require including addtional entity in our database, which we are for now considering a future work.

In [109]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy import text

In [110]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [111]:
# Loading the database schema

load_dotenv()
password = os.getenv("DB_PASSWORD")
os.environ["DATABASE_URL"] = f"mysql+pymysql://root:{password}@localhost/animal_extinction_db"
engine = create_engine(os.environ["DATABASE_URL"])

In [112]:
tsx = pd.read_csv("../Data/tsx_cleaned.csv", dtype=str, low_memory=False)
endangerment = pd.read_csv("../Data/Threatened_Species_State_Lists_cleaned.csv", dtype=str, low_memory=False)

In [113]:
tsx.shape

(141, 79)

In [114]:
endangerment.shape

(700, 24)

As demostrated below, only 5 animals are shared between the datasets.
Thus, it does not make sence to merge the datasets, we just need to make sure to correctly handle the five duplicates.

In [115]:
for d in (tsx, endangerment):
    d["Scientific Name"] = d["Scientific Name"].astype(str).str.strip().str.lower()

combined = tsx.merge(endangerment, on="Scientific Name", how="inner")
combined.shape
combined.head()

,Unnamed: 0_x,Scientific Name,Common_Name,Class_x,State,Level_x,1950,1951,1952,1953,...,CSI,JBT,NFI,HMI,AAT,CMA,Kingdom,Class_y,Level_y,Year
0,0,amytornis barbatus barbatus,Bulloo Grey Grasswren,Aves,New South Wales,EN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,EN,2026
1,1,amytornis striatus howei,Murray Mallee Striated Grasswren,Aves,New South Wales,EN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,EN,2026
2,2,antechinus arktos,Black-tailed Antechinus,Mammalia,New South Wales,EN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Mammalia,EN,2026
3,3,antechinus arktos,Black-tailed Antechinus,Mammalia,Queensland,EN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Mammalia,EN,2026
4,4,antechinus bellus,Fawn Antechinus,Mammalia,Northern Territory,VU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Mammalia,VU,2026

# Inserting TSX dataset

The index is managed by the NCRIS-funded Terrestrial Ecosystem Research Network (TERN) project at The University of Queensland and supported by the Australian Government Department of Climate Change, Energy, the Environment and Water (DCCEEW).

All TSX data available at https://tsx.org.au/tsx/ are openly accessible and are licensed under a Creative Commons – Attribution 4.0 International licence (CC BY 4.0).

Publication date of the data: 25-11-2025

The dataset contains:

1) 193,500 yearly population values (1950–2022) from 25,164 monitored time series, for 217 animal species and 178 plant taxa. Plants are left out in our database as we focus only on animals.

2) Per value the data contains: species, site, region, unit of measurement (there are 103 different possible units), year and the population 

3) There are 15,724 monitoring sites in 346 regions

For the purposes of our database, the dataset has been heavily filtered to match our schema.

In [116]:
from sqlalchemy import inspect
inspect(engine).get_schema_names()

['animal_extinction_db',
 'information_schema',
 'mysql',
 'performance_schema',
 'sakila',
 'sys']

In [117]:
tsx.columns

Index(['Unnamed: 0', 'Scientific Name', 'Common_Name', 'Class', 'State',
       'Level', '1950', '1951', '1952', '1953', '1954', '1955', '1956', '1957',
       '1958', '1959', '1960', '1961', '1962', '1963', '1964', '1965', '1966',
       '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975',
       '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022'],
      dtype='str')

### Inserting the states (locations)

In [118]:
print(tsx["State"].unique())

<StringArray>
[             'New South Wales',                   'Queensland',
           'Northern Territory',            'Western Australia',
              'South Australia', 'Australian Capital Territory',
                     'Tasmania',                     'Victoria',
                 'Commonwealth']
Length: 9, dtype: str

In [119]:
names = ["New South Wales", "Northern Territory", "South Australia", "Tasmania",
         "Commonwealth", "Queensland", "Western Australia",
         "Australian Capital Territory", "Victoria"]

with engine.begin() as conn:
    conn.execute(
        text("INSERT INTO animal_extinction_db.location (location_name) VALUES (:name)"),
        [{"name": n} for n in names],
    )

In [120]:
%%sql

# Checking the insertion
SELECT *
FROM location

 * mysql+pymysql://root:***@localhost/animal_extinction_db
9 rows affected.

[(1, 'New South Wales', None, None, None),
 (2, 'Northern Territory', None, None, None),
 (3, 'South Australia', None, None, None),
 (4, 'Tasmania', None, None, None),
 (5, 'Commonwealth', None, None, None),
 (6, 'Queensland', None, None, None),
 (7, 'Western Australia', None, None, None),
 (8, 'Australian Capital Territory', None, None, None),
 (9, 'Victoria', None, None, None)]

### Inserting available Animal data into Animal entity (TSX data)

In [121]:
# Inserting the Animal data by creating a temporary table from the pre-processed dataset

# Original dataset has multiple rows for one animal (because of multiple locations)
#   -> we need to collapse it to one to meet UNIQUE NOT NULL constraint for scientific_name
# Also we need to rename the cols to match the column names in the database

# Striping all text columns
str_cols = tsx.select_dtypes(include=["object", "string"]).columns
tsx[str_cols] = tsx[str_cols].apply(lambda s: s.str.strip())

# Putting the scientific name to lowercase
tsx["Scientific Name"] = tsx["Scientific Name"].str.strip()

unique_animals = (
    tsx[["Scientific Name", "Common_Name", "Class"]]
    .drop_duplicates(subset="Scientific Name")
    .rename(columns={
        "Scientific Name": "scientific_name",
        "Common_Name": "common_name",
        "Class": "class",
    })
)
# NaN in a NOT NULL column
print(unique_animals.isna().sum())

scientific_name    0
common_name        0
class              0
dtype: int64

In [122]:
# Actually inserting the available animal data into the Animal entity

with engine.begin() as conn:
    unique_animals.to_sql("tsx_staging", conn, schema="animal_extinction_db",
                          if_exists="replace", index=False)

    conn.execute(text("""
        INSERT INTO animal_extinction_db.animal (scientific_name, common_name, animal_class)
        SELECT scientific_name, common_name, class
        FROM animal_extinction_db.tsx_staging

    """))
    conn.execute(text("DROP TABLE animal_extinction_db.tsx_staging"))

In [123]:
%%sql
# Checking the insertion
SELECT *
FROM Animal;

 * mysql+pymysql://root:***@localhost/animal_extinction_db
62 rows affected.

[(1, 'amytornis barbatus barbatus', 'Bulloo Grey Grasswren', 'Aves', None, None),
 (2, 'amytornis striatus howei', 'Murray Mallee Striated Grasswren', 'Aves', None, None),
 (3, 'antechinus arktos', 'Black-tailed Antechinus', 'Mammalia', None, None),
 (4, 'antechinus bellus', 'Fawn Antechinus', 'Mammalia', None, None),
 (5, 'atrichornis rufescens ferrieri', 'Southern Rufous Scrub-bird', 'Aves', None, None),
 (6, 'atrichornis rufescens rufescens', 'Northern Rufous Scrub-bird', 'Aves', None, None),
 (7, 'bettongia lesueur lesueur', 'Burrowing Bettong', 'Mammalia', None, None),
 (8, 'bettongia penicillata ogilbyi', 'Woylie', 'Mammalia', None, None),
 (9, 'botaurus poiciloptilus', 'Australasian Bittern', 'Aves', None, None),
 (10, 'burramys parvus', 'Mountain Pygmy-possum', 'Mammalia', None, None),
 (11, 'calidris acuminata', 'Sharp-tailed Sandpiper', 'Aves', None, None),
 (12, 'calidris canutus', 'Red Knot', 'Aves', None, None),
 (13, 'calidris ferruginea', 'Curlew Sandpiper', 'Aves', None, None),
 (14, 'calidris tenuirostris', 'Great Knot', 'Aves', None, None),
 (15, 'calyptorhynchus banksii naso', 'Forest Red-tailed Black-Cockatoo', 'Aves', None, None),
 (16, 'calyptorhynchus lathami halmaturinus', 'Kangaroo Island Glossy Black-Cockatoo', 'Aves', None, None),
 (17, 'chalinolobus dwyeri', 'Large Pied Bat', 'Mammalia', None, None),
 (18, 'charadrius leschenaultii', 'Greater Sand Plover', 'Aves', None, None),
 (19, 'charadrius mongolus', 'Lesser Sand Plover', 'Aves', None, None),
 (20, 'chloebia gouldiae', 'Gouldian Finch', 'Aves', None, None),
 (21, 'climacteris picumnus victoriae', 'South-eastern Brown Treecreeper', 'Aves', None, None),
 (22, 'conilurus penicillatus', 'Brush-tailed Rabbit-rat', 'Mammalia', None, None),
 (23, 'conilurus penicillatus melibius', 'Brush-tailed Rabbit-rat', 'Mammalia', None, None),
 (24, 'dasyurus hallucatus', 'Digul', 'Mammalia', None, None),
 (25, 'epthianura crocea macgregori', 'Capricorn Yellow Chat', 'Aves', None, None),
 (26, 'epthianura crocea tunneyi', 'Alligator Rivers Yellow Chat', 'Aves', None, None),
 (27, 'gymnobelideus leadbeateri', "Leadbeater's Possum", 'Mammalia', None, None),
 (28, 'isoodon obesulus obesulus', 'Southern Brown Bandicoot', 'Mammalia', None, None),
 (29, 'lagorchestes hirsutus subsp', 'Mala', 'Mammalia', None, None),
 (30, 'lichenostomus melanops cassidix', 'Helmeted Honeyeater', 'Aves', None, None),
 (31, 'limosa lapponica baueri', 'Alaskan Bar-tailed Godwit', 'Aves', None, None),
 (32, 'limosa lapponica menzbieri', 'Yakutian Bar-tailed Godwit', 'Aves', None, None),
 (33, 'limosa limosa', 'Black-tailed Godwit', 'Aves', None, None),
 (34, 'macronectes giganteus', 'Southern Giant-Petrel', 'Aves', None, None),
 (35, 'malurus coronatus coronatus', 'Western Purple-crowned Fairy-wren', 'Aves', None, None),
 (36, 'mesembriomys gouldii gouldii', 'Black-footed Tree-rat', 'Mammalia', None, None),
 (37, 'mesembriomys gouldii melvillensis', 'Black-footed Tree-rat', 'Mammalia', None, None),
 (38, 'mirounga leonina', 'Southern Elephant Seal', 'Mammalia', None, None),
 (39, 'neophema chrysogaster', 'Orange-bellied Parrot', 'Aves', None, None),
 (40, 'numenius madagascariensis', 'Far Eastern Curlew', 'Aves', None, None),
 (41, 'onychogalea fraenata', 'Bridled Nailtail Wallaby', 'Mammalia', None, None),
 (42, 'petauroides volans', 'Southern Greater Glider', 'Mammalia', None, None),
 (43, 'petrogale lateralis lateralis', 'Black-flanked Rock-wallaby', 'Mammalia', None, None),
 (44, 'petrogale sharmani', "Sharman's Rock-wallaby", 'Mammalia', None, None),
 (45, 'phascolarctos cinereus', 'Koala', 'Mammalia', None, None),
 (46, 'poephila cincta cincta', 'Southern Black-throated Finch', 'Aves', None, None),
 (47, 'pseudocheirus occidentalis', 'Western Ringtail Possum', 'Mammalia', None, None),
 (48, 'pseudomys novaehollandiae', 'New Holland Mouse', 'Mammalia', None, None),
 (49, 'pterodroma neglecta neglecta', 'Western Kermadec Petrel', 'Aves', None, None),
 (50, 'pteropus conspicillatus', 'Spectacled Flying-fox', 'Mammalia', None, None),
 (51, 'pteropus natalis', 'Christmas Island Flying Fox', 'Mammalia', None, None),
 (52, 'pteropus poliocephalus', 'Grey-headed Flying-fox', 'Mammalia', None, None),
 (53, 'sminthopsis fuliginosus aitkeni', 'Kangaroo Island Dunnart', 'Mammalia', None, None),
 (54, 'sternula nereis nereis', 'Australian Fairy Tern', 'Aves', None, None),
 (55, 'strepera graculina crissalis', 'Lord Howe Pied Currawong', 'Aves', None, None),
 (56, 'tachyglossus aculeatus multiaculeatus', 'Kangaroo Island Echidna', 'Mammalia', None, None),
 (57, 'tringa nebularia', 'Common Greenshank', 'Aves', None, None),
 (58, 'xenus cinereus', 'Terek Sandpiper', 'Aves', None, None),
 (59, 'xeromys myoides', 'False Water-rat', 'Mammalia', None, None),
 (60, 'zanda baudinii', "Baudin's Black-Cockatoo", 'Aves', None, None),
 (61, 'zanda latirostris', "Carnaby's Black-Cockatoo", 'Aves', None, None),
 (62, 'zyzomys maini', 'Arnhem Land Rock-rat', 'Mammalia', None, None)]

### Populating the Population_of_Animal entity (TSX data)

In [124]:
# We need to first colapse the year columns into indiviudal rows -> in one row: animal, state, one year, population

year_cols = [c for c in tsx.columns if str(c).isdigit()]

pop = tsx.melt(
    id_vars=["Scientific Name", "State"],
    value_vars=year_cols,
    var_name="population_year",
    value_name="population_size",
)
pop["population_year"] = pop["population_year"].astype(int)
pop = pop.dropna(subset=["population_size"])   # population_size is NOT NULL -> drop all null rows in population_size

pop.head()

            Scientific Name         State  population_year population_size
2360     petauroides volans      Victoria             1966             1.0
2485  macronectes giganteus  Commonwealth             1967            17.0
2501     petauroides volans      Victoria             1967            29.5
2642     petauroides volans      Victoria             1968            13.0
2783     petauroides volans      Victoria             1969            27.0

In [125]:
# Adding the animal and location ids from the database based on 
# a name match into the pop dataframe

animal_ids = pd.read_sql(
    "SELECT animal_id, scientific_name FROM animal_extinction_db.animal", engine)
location_ids = pd.read_sql(
    "SELECT location_id, location_name FROM animal_extinction_db.location", engine)

pop = (
    pop.merge(animal_ids, left_on="Scientific Name", right_on="scientific_name", how="left")
       .merge(location_ids, left_on="State", right_on="location_name", how="left")
)

pop.head()

,Scientific Name,State,population_year,population_size,animal_id,scientific_name,location_id,location_name
0,petauroides volans,Victoria,1966,1.0,42,petauroides volans,9,Victoria
1,macronectes giganteus,Commonwealth,1967,17.0,34,macronectes giganteus,5,Commonwealth
2,petauroides volans,Victoria,1967,29.5,42,petauroides volans,9,Victoria
3,petauroides volans,Victoria,1968,13.0,42,petauroides volans,9,Victoria
4,petauroides volans,Victoria,1969,27.0,42,petauroides volans,9,Victoria

In [126]:
# Keeping only relevant cols
final = pop[["animal_id", "location_id", "population_year", "population_size"]]

# Checking everything has been properly matched (yes = all zeros)
print(pop["animal_id"].isna().sum(), pop["location_id"].isna().sum())

0 0

In [127]:
# Checking the data before insertion 

final = pop[["animal_id", "location_id", "population_year", "population_size"]].copy()
final = final.astype({"animal_id": int, "location_id": int, "population_year": int})

# Missing IDs or values
print(final.isna().sum())

# Primary key: one row per animal, location, year
print("PK duplicates:", final.duplicated(["animal_id", "location_id", "population_year"]).sum())

# Constraint and type limits
print("max size:", final["population_size"].max())   # DECIMAL(16,9) caps at just under 10,000,000
print("min size:", final["population_size"].min())   # must be >= 0
print("years:", final["population_year"].min(), final["population_year"].max())

animal_id          0
location_id        0
population_year    0
population_size    0
dtype: int64
PK duplicates: 0
max size: 9989.0
min size: 0.0
years: 1966 2022

In [128]:
# Inserting in into the database
final.to_sql("Population_of_Animal", engine, schema="animal_extinction_db",
             if_exists="append", index=False, method="multi", chunksize=1000)

C:\Users\Latitude\AppData\Local\Temp\ipykernel_29768\1692850824.py:2: UserWarning: The provided table name 'Population_of_Animal' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  final.to_sql("Population_of_Animal", engine, schema="animal_extinction_db",

3290

In [129]:
%%sql
SELECT *
FROM Population_of_Animal

 * mysql+pymysql://root:***@localhost/animal_extinction_db
3290 rows affected.

[(1, 1, 2015, Decimal('1.166666600')),
 (1, 1, 2017, Decimal('3.499999900')),
 (1, 1, 2018, Decimal('2.000000000')),
 (1, 1, 2019, Decimal('2.160714200')),
 (1, 1, 2021, Decimal('21.500000000')),
 (2, 1, 2012, Decimal('1.750000000')),
 (2, 1, 2013, Decimal('2.333333000')),
 (2, 1, 2015, Decimal('3.500000000')),
 (4, 2, 1995, Decimal('1.000000000')),
 (4, 2, 1996, Decimal('11.000000000')),
 (4, 2, 2001, Decimal('35.000000000')),
 (4, 2, 2002, Decimal('17.000000000')),
 (4, 2, 2003, Decimal('0E-9')),
 (4, 2, 2004, Decimal('0E-9')),
 (4, 2, 2006, Decimal('3.000000000')),
 (4, 2, 2008, Decimal('5.000000000')),
 (4, 2, 2009, Decimal('0E-9')),
 (4, 2, 2011, Decimal('1.000000000')),
 (4, 2, 2013, Decimal('8.000000000')),
 (4, 2, 2014, Decimal('2.000000000')),
 (4, 2, 2016, Decimal('2.000000000')),
 (5, 1, 2010, Decimal('5.916666700')),
 (5, 1, 2011, Decimal('8.750000000')),
 (5, 1, 2012, Decimal('10.500000000')),
 (5, 1, 2013, Decimal('4.500000000')),
 (5, 1, 2016, Decimal('5.999999900')),
 (5, 1, 2017, Decimal('5.000000100')),
 (5, 1, 2018, Decimal('8.750000000')),
 (5, 1, 2020, Decimal('3.666666300')),
 (5, 1, 2021, Decimal('4.666666700')),
 (6, 1, 2006, Decimal('1.000000000')),
 (6, 1, 2007, Decimal('0E-9')),
 (6, 1, 2010, Decimal('12.000000000')),
 (6, 1, 2011, Decimal('11.000000000')),
 (6, 1, 2012, Decimal('7.000000000')),
 (6, 1, 2013, Decimal('15.000000000')),
 (6, 1, 2014, Decimal('15.500000000')),
 (6, 1, 2015, Decimal('12.000000000')),
 (6, 1, 2016, Decimal('2.500000000')),
 (6, 1, 2018, Decimal('13.000000000')),
 (6, 1, 2019, Decimal('7.000000000')),
 (6, 1, 2020, Decimal('11.000000000')),
 (6, 1, 2021, Decimal('8.000000000')),
 (6, 6, 2006, Decimal('5.500000000')),
 (6, 6, 2007, Decimal('3.000000000')),
 (6, 6, 2010, Decimal('0E-9')),
 (6, 6, 2013, Decimal('3.000000000')),
 (6, 6, 2014, Decimal('3.500000000')),
 (6, 6, 2015, Decimal('0E-9')),
 (6, 6, 2016, Decimal('6.000000000')),
 (7, 7, 2016, Decimal('482.000000000')),
 (7, 7, 2017, Decimal('596.000000000')),
 (7, 7, 2018, Decimal('427.000000000')),
 (7, 7, 2019, Decimal('704.000000000')),
 (7, 7, 2022, Decimal('554.000000000')),
 (8, 7, 2016, Decimal('106.000000000')),
 (8, 7, 2017, Decimal('169.000000000')),
 (8, 7, 2018, Decimal('168.000000000')),
 (8, 7, 2019, Decimal('156.000000000')),
 (8, 7, 2020, Decimal('161.000000000')),
 (8, 7, 2021, Decimal('149.000000000')),
 (9, 3, 2016, Decimal('1.250000000')),
 (9, 3, 2017, Decimal('0.833333333')),
 (9, 3, 2018, Decimal('2.916666667')),
 (9, 3, 2019, Decimal('3.250000000')),
 (10, 1, 1986, Decimal('31.000000000')),
 (10, 1, 1987, Decimal('120.000000000')),
 (10, 1, 1988, Decimal('136.000000000')),
 (10, 1, 1989, Decimal('124.000000000')),
 (10, 1, 1990, Decimal('104.000000000')),
 (10, 1, 1991, Decimal('129.000000000')),
 (10, 1, 1992, Decimal('87.000000000')),
 (10, 1, 1993, Decimal('136.000000000')),
 (10, 1, 1994, Decimal('99.000000000')),
 (10, 1, 1995, Decimal('123.000000000')),
 (10, 1, 1996, Decimal('125.000000000')),
 (10, 1, 1997, Decimal('151.000000000')),
 (10, 1, 1998, Decimal('117.000000000')),
 (10, 1, 1999, Decimal('97.000000000')),
 (10, 1, 2000, Decimal('83.000000000')),
 (10, 1, 2001, Decimal('77.000000000')),
 (10, 1, 2002, Decimal('115.000000000')),
 (10, 1, 2003, Decimal('79.000000000')),
 (10, 1, 2004, Decimal('47.000000000')),
 (10, 1, 2005, Decimal('69.000000000')),
 (10, 1, 2006, Decimal('64.000000000')),
 (10, 1, 2007, Decimal('59.000000000')),
 (10, 1, 2008, Decimal('54.000000000')),
 (10, 1, 2009, Decimal('70.000000000')),
 (10, 1, 2010, Decimal('81.000000000')),
 (10, 1, 2011, Decimal('152.000000000')),
 (10, 1, 2012, Decimal('132.000000000')),
 (10, 1, 2013, Decimal('153.000000000')),
 (10, 1, 2014, Decimal('182.000000000')),
 (10, 1, 2015, Decimal('175.000000000')),
 (10, 1, 2016, Decimal('165.000000000')),
 (10, 1, 2017, Decimal('198.000000000')),
 (10, 1, 2018, Decimal('119.000000000')),
 (10, 1, 2019, Decimal('142.000000000')),
 (11, 1, 1992, Decimal('3.000000000')),
 (11, 1, 1993, Decimal('55.000000000')),
 (11, 1, 1994, Decimal('284.000000000')),
 (11, 1, 1995, Decimal('633.000000000')),
 (11, 1, 1996, Decimal('229.000000000')),
 (11, 1, 1997, Decimal('179.000000000')),
 (11, 1, 1998, Decimal('65.000000000')),
 (11, 1, 1999, Decimal('186.000000000')),
 (11, 1, 2000, Decimal('18.000000000')),
 (11, 1, 2001, Decimal('6.000000000')),
 (11, 1, 2002, Decimal('576.000000000')),
 (11, 1, 2003, Decimal('3731.000000000')),
 (11, 1, 2004, Decimal('387.000000000')),
 (11, 1, 2005, Decimal('205.000000000')),
 (11, 1, 2006, Decimal('241.000000000')),
 (11, 1, 2007, Decimal('726.000000000')),
 (11, 1, 2008, Decimal('60.000000000')),
 (11, 1, 2009, Decimal('616.000000000')),
 (11, 1, 2010, Decimal('307.000000000')),
 (11, 1, 2011, Decimal('2.000000000')),
 (11, 1, 2012, Decimal('125.000000000')),
 (11, 1, 2013, Decimal('477.000000000')),
 (11, 1, 2014, Decimal('4107.000000000')),
 (11, 1, 2015, Decimal('1820.000000000')),
 (11, 1, 2016, Decimal('4224.000000000')),
 (11, 1, 2017, Decimal('1209.000000000')),
 (11, 1, 2018, Decimal('2105.000000000')),
 (11, 1, 2019, Decimal('3462.000000000')),
 (11, 1, 2020, Decimal('576.000000000')),
 (11, 1, 2021, Decimal('282.000000000')),
 (11, 1, 2022, Decimal('102.000000000')),
 (11, 2, 1992, Decimal('10.000000000')),
 (11, 2, 1994, Decimal('6.000000000')),
 (11, 2, 1995, Decimal('11.000000000')),
 (11, 2, 1996, Decimal('8.000000000')),
 (11, 2, 1997, Decimal('3.000000000')),
 (11, 2, 2000, Decimal('9.000000000')),
 (11, 2, 2001, Decimal('5.000000000')),
 (11, 2, 2002, Decimal('0E-9')),
 (11, 2, 2003, Decimal('0E-9')),
 (11, 2, 2004, Decimal('11.000000000')),
 (11, 2, 2005, Decimal('5.000000000')),
 (11, 2, 2006, Decimal('10.000000000')),
 (11, 2, 2007, Decimal('17.000000000')),
 (11, 2, 2008, Decimal('0E-9')),
 (11, 2, 2009, Decimal('8.000000000')),
 (11, 2, 2010, Decimal('272.000000000')),
 (11, 2, 2011, Decimal('0E-9')),
 (11, 2, 2012, Decimal('13.000000000')),
 (11, 2, 2013, Decimal('25.000000000')),
 (11, 2, 2014, Decimal('199.000000000')),
 (11, 2, 2015, Decimal('65.000000000')),
 (11, 2, 2016, Decimal('1163.000000000')),
 (11, 2, 2017, Decimal('0E-9')),
 (11, 2, 2018, Decimal('29.000000000')),
 (11, 2, 2019, Decimal('13.000000000')),
 (11, 2, 2020, Decimal('97.000000000')),
 (11, 2, 2021, Decimal('25.000000000')),
 (11, 2, 2022, Decimal('32.000000000')),
 (11, 3, 1992, Decimal('112.000000000')),
 (11, 3, 1993, Decimal('1733.000000000')),
 (11, 3, 1994, Decimal('173.000000000')),
 (11, 3, 1995, Decimal('2867.000000000')),
 (11, 3, 1996, Decimal('1245.000000000')),
 (11, 3, 1997, Decimal('1618.000000000')),
 (11, 3, 1998, Decimal('303.000000000')),
 (11, 3, 1999, Decimal('145.000000000')),
 (11, 3, 2000, Decimal('15153.000000000')),
 (11, 3, 2001, Decimal('4759.000000000')),
 (11, 3, 2002, Decimal('20732.000000000')),
 (11, 3, 2003, Decimal('7868.000000000')),
 (11, 3, 2004, Decimal('3174.000000000')),
 (11, 3, 2005, Decimal('16380.000000000')),
 (11, 3, 2006, Decimal('18097.000000000')),
 (11, 3, 2007, Decimal('977.000000000')),
 (11, 3, 2008, Decimal('4055.000000000')),
 (11, 3, 2009, Decimal('3851.000000000')),
 (11, 3, 2010, Decimal('22258.000000000')),
 (11, 3, 2011, Decimal('1276.000000000')),
 (11, 3, 2012, Decimal('15449.000000000')),
 (11, 3, 2013, Decimal('6638.000000000')),
 (11, 3, 2014, Decimal('3204.000000000')),
 (11, 3, 2015, Decimal('1382.000000000')),
 (11, 3, 2016, Decimal('5512.000000000')),
 (11, 3, 2017, Decimal('7965.000000000')),
 (11, 3, 2018, Decimal('10160.000000000')),
 (11, 3, 2019, Decimal('33033.000000000')),
 (11, 3, 2020, Decimal('10437.000000000')),
 (11, 3, 2021, Decimal('11734.000000000')),
 (11, 3, 2022, Decimal('7719.000000000')),
 (11, 4, 1992, Decimal('76.000000000')),
 (11, 4, 1993, Decimal('11.000000000')),
 (11, 4, 1994, Decimal('11.000000000')),
 (11, 4, 1995, Decimal('52.000000000')),
 (11, 4, 1996, Decimal('26.000000000')),
 (11, 4, 1997, Decimal('28.000000000')),
 (11, 4, 1998, Decimal('80.000000000')),
 (11, 4, 1999, Decimal('63.000000000')),
 (11, 4, 2000, Decimal('23.000000000')),
 (11, 4, 2001, Decimal('9.000000000')),
 (11, 4, 2002, Decimal('2.000000000')),
 (11, 4, 2003, Decimal('152.000000000')),
 (11, 4, 2004, Decimal('120.000000000')),
 (11, 4, 2005, Decimal('22.000000000')),
 (11, 4, 2006, Decimal('192.000000000')),
 (11, 4, 2007, Decimal('71.000000000')),
 (11, 4, 2008, Decimal('139.000000000')),
 (11, 4, 2009, Decimal('89.000000000')),
 (11, 4, 2010, Decimal('420.000000000')),
 (11, 4, 2011, Decimal('36.000000000')),
 (11, 4, 2012, Decimal('105.000000000')),
 (11, 4, 2013, Decimal('156.000000000')),
 (11, 4, 2014, Decimal('63.000000000')),
 (11, 4, 2015, Decimal('56.000000000')),
 (11, 4, 2016, Decimal('73.000000000')),
 (11, 4, 2017, Decimal('31.000000000')),
 (11, 4, 2018, Decimal('7.000000000')),
 (11, 4, 2019, Decimal('25.000000000')),
 (11, 4, 2020, Decimal('39.000000000')),
 (11, 4, 2021, Decimal('7.000000000')),
 (11, 4, 2022, Decimal('29.000000000')),
 (11, 6, 1992, Decimal('361.000000000')),
 (11, 6, 1993, Decimal('240.000000000')),
 (11, 6, 1994, Decimal('596.000000000')),
 (11, 6, 1995, Decimal('1043.000000000')),
 (11, 6, 1996, Decimal('1531.000000000')),
 (11, 6, 1997, Decimal('303.000000000')),
 (11, 6, 1998, Decimal('714.000000000')),
 (11, 6, 1999, Decimal('659.000000000')),
 (11, 6, 2000, Decimal('376.000000000')),
 (11, 6, 2001, Decimal('236.000000000')),
 (11, 6, 2002, Decimal('976.000000000')),
 (11, 6, 2003, Decimal('1586.000000000')),
 (11, 6, 2004, Decimal('1374.000000000')),
 (11, 6, 2005, Decimal('1357.000000000')),
 (11, 6, 2006, Decimal('3587.000000000')),
 (11, 6, 2007, Decimal('1544.000000000')),
 (11, 6, 2008, Decimal('1364.000000000')),
 (11, 6, 2009, Decimal('1101.000000000')),
 (11, 6, 2010, Decimal('1056.000000000')),
 (11, 6, 2011, Decimal('784.000000000')),
 (11, 6, 2012, Decimal('2920.000000000')),
 (11, 6, 2013, Decimal('1168.000000000')),
 (11, 6, 2014, Decimal('519.000000000')),
 (11, 6, 2015, Decimal('1556.000000000')),
 (11, 6, 2016, Decimal('904.000000000')),
 (11, 6, 2017, Decimal('699.000000000')),
 (11, 6, 2018, Decimal('1213.000000000')),
 (11, 6, 2019, Decimal('867.000000000')),
 (11, 6, 2020, Decimal('1226.000000000')),
 (11, 6, 2021, Decimal('1958.000000000')),
 (11, 6, 2022, Decimal('1355.000000000')),
 (11, 7, 1992, Decimal('205.000000000')),
 (11, 7, 1993, Decimal('92.000000000')),
 (11, 7, 1994, Decimal('1754.000000000')),
 (11, 7, 1995, Decimal('337.000000000')),
 (11, 7, 1996, Decimal('372.000000000')),
 (11, 7, 1997, Decimal('469.000000000')),
 (11, 7, 1998, Decimal('4243.000000000')),
 (11, 7, 1999, Decimal('1861.000000000')),
 (11, 7, 2000, Decimal('303.000000000')),
 (11, 7, 2001, Decimal('109.000000000')),
 (11, 7, 2002, Decimal('237.000000000')),
 (11, 7, 2003, Decimal('2367.000000000')),
 (11, 7, 2004, Decimal('1680.000000000')),
 (11, 7, 2005, Decimal('3308.000000000')),
 (11, 7, 2006, Decimal('8374.000000000')),
 (11, 7, 2007, Decimal('4744.000000000')),
 (11, 7, 2008, Decimal('2358.000000000')),
 (11, 7, 2009, Decimal('3725.000000000')),
 (11, 7, 2010, Decimal('4504.000000000')),
 (11, 7, 2011, Decimal('2741.000000000')),
 (11, 7, 2012, Decimal('1394.000000000')),
 (11, 7, 2013, Decimal('3657.000000000')),
 (11, 7, 2014, Decimal('7006.000000000')),
 (11, 7, 2015, Decimal('6635.000000000')),
 (11, 7, 2016, Decimal('2020.000000000')),
 (11, 7, 2017, Decimal('1467.000000000')),
 (11, 7, 2018, Decimal('3159.000000000')),
 (11, 7, 2019, Decimal('4217.000000000')),
 (11, 7, 2020, Decimal('4782.000000000')),
 (11, 7, 2021, Decimal('2579.000000000')),
 (11, 7, 2022, Decimal('1209.000000000')),
 (11, 8, 2002, Decimal('0E-9')),
 (11, 8, 2003, Decimal('2.000000000')),
 (11, 8, 2004, Decimal('8.000000000')),
 (11, 8, 2007, Decimal('1.000000000')),
 (11, 8, 2008, Decimal('0E-9')),
 (11, 8, 2009, Decimal('1.000000000')),
 (11, 8, 2020, Decimal('3.000000000')),
 (11, 9, 1992, Decimal('5396.000000000')),
 (11, 9, 1993, Decimal('1710.000000000')),
 (11, 9, 1994, Decimal('7625.000000000')),
 (11, 9, 1995, Decimal('6389.000000000')),
 (11, 9, 1996, Decimal('1904.000000000')),
 (11, 9, 1997, Decimal('3982.000000000')),
 (11, 9, 1998, Decimal('5022.000000000')),
 (11, 9, 1999, Decimal('2903.000000000')),
 (11, 9, 2000, Decimal('6954.000000000')),
 (11, 9, 2001, Decimal('4595.000000000')),
 (11, 9, 2002, Decimal('5339.000000000')),
 (11, 9, 2003, Decimal('6317.000000000')),
 (11, 9, 2004, Decimal('8193.000000000')),
 (11, 9, 2005, Decimal('8600.000000000')),
 (11, 9, 2006, Decimal('15208.000000000')),
 (11, 9, 2007, Decimal('7551.000000000')),
 (11, 9, 2008, Decimal('11855.000000000')),
 (11, 9, 2009, Decimal('3418.000000000')),
 (11, 9, 2010, Decimal('11128.000000000')),
 (11, 9, 2011, Decimal('120.000000000')),
 (11, 9, 2012, Decimal('3385.000000000')),
 (11, 9, 2013, Decimal('6783.000000000')),
 (11, 9, 2014, Decimal('5733.000000000')),
 (11, 9, 2015, Decimal('5179.000000000')),
 (11, 9, 2016, Decimal('5874.000000000')),
 (11, 9, 2017, Decimal('3114.000000000')),
 (11, 9, 2018, Decimal('19834.000000000')),
 (11, 9, 2019, Decimal('8343.000000000')),
 (11, 9, 2020, Decimal('13793.000000000')),
 (11, 9, 2021, Decimal('5532.000000000')),
 (11, 9, 2022, Decimal('1670.000000000')),
 (12, 1, 1997, Decimal('15.000000000')),
 (12, 1, 1998, Decimal('62.000000000')),
 (12, 1, 1999, Decimal('45.000000000')),
 (12, 1, 2000, Decimal('716.000000000')),
 (12, 1, 2001, Decimal('18.000000000')),
 (12, 1, 2002, Decimal('44.000000000')),
 (12, 1, 2003, Decimal('62.000000000')),
 (12, 1, 2004, Decimal('39.000000000')),
 (12, 1, 2005, Decimal('58.000000000')),
 (12, 1, 2006, Decimal('63.000000000')),
 (12, 1, 2007, Decimal('376.000000000')),
 (12, 1, 2008, Decimal('33.000000000')),
 (12, 1, 2009, Decimal('30.000000000')),
 (12, 1, 2010, Decimal('19.000000000')),
 (12, 1, 2011, Decimal('18.000000000')),
 (12, 1, 2012, Decimal('38.000000000')),
 (12, 1, 2013, Decimal('28.000000000')),
 (12, 1, 2014, Decimal('19.000000000')),
 (12, 1, 2015, Decimal('88.000000000')),
 (12, 1, 2016, Decimal('84.000000000')),
 (12, 1, 2017, Decimal('49.000000000')),
 (12, 1, 2018, Decimal('92.000000000')),
 (12, 1, 2019, Decimal('70.000000000')),
 (12, 1, 2020, Decimal('69.000000000')),
 (12, 1, 2021, Decimal('162.000000000')),
 (12, 1, 2022, Decimal('10.000000000')),
 (12, 2, 1997, Decimal('0E-9')),
 (12, 2, 2000, Decimal('0E-9')),
 (12, 2, 2002, Decimal('30.000000000')),
 (12, 2, 2003, Decimal('100.000000000')),
 (12, 2, 2004, Decimal('158.000000000')),
 (12, 2, 2005, Decimal('133.000000000')),
 (12, 2, 2006, Decimal('283.000000000')),
 (12, 2, 2007, Decimal('124.000000000')),
 (12, 2, 2008, Decimal('201.000000000')),
 (12, 2, 2009, Decimal('106.000000000')),
 (12, 2, 2010, Decimal('208.000000000')),
 (12, 2, 2011, Decimal('208.000000000')),
 (12, 2, 2012, Decimal('78.000000000')),
 (12, 2, 2013, Decimal('170.000000000')),
 (12, 2, 2014, Decimal('240.000000000')),
 (12, 2, 2015, Decimal('248.000000000')),
 (12, 2, 2016, Decimal('882.000000000')),
 (12, 2, 2017, Decimal('396.000000000')),
 (12, 2, 2018, Decimal('149.000000000')),
 (12, 2, 2019, Decimal('395.000000000')),
 (12, 2, 2020, Decimal('135.000000000')),
 (12, 2, 2021, Decimal('178.000000000')),
 (12, 2, 2022, Decimal('86.000000000')),
 (12, 3, 1999, Decimal('2.000000000')),
 (12, 3, 2000, Decimal('9244.000000000')),
 (12, 3, 2001, Decimal('653.000000000')),
 (12, 3, 2002, Decimal('39.000000000')),
 (12, 3, 2003, Decimal('90.000000000')),
 (12, 3, 2004, Decimal('418.000000000')),
 (12, 3, 2005, Decimal('11.000000000')),
 (12, 3, 2006, Decimal('2.000000000')),
 (12, 3, 2007, Decimal('0E-9')),
 (12, 3, 2008, Decimal('3031.000000000')),
 (12, 3, 2009, Decimal('4019.000000000')),
 (12, 3, 2010, Decimal('2306.000000000')),
 (12, 3, 2011, Decimal('1592.000000000')),
 (12, 3, 2012, Decimal('1750.000000000')),
 (12, 3, 2013, Decimal('2674.000000000')),
 (12, 3, 2014, Decimal('2099.000000000')),
 (12, 3, 2015, Decimal('3490.000000000')),
 (12, 3, 2016, Decimal('2288.000000000')),
 (12, 3, 2017, Decimal('1123.000000000')),
 (12, 3, 2018, Decimal('5165.000000000')),
 (12, 3, 2019, Decimal('4510.000000000')),
 (12, 3, 2020, Decimal('1771.000000000')),
 (12, 3, 2021, Decimal('3483.000000000')),
 (12, 3, 2022, Decimal('1867.000000000')),
 (12, 4, 1997, Decimal('837.000000000')),
 (12, 4, 1998, Decimal('820.000000000')),
 (12, 4, 1999, Decimal('806.000000000')),
 (12, 4, 2000, Decimal('4.000000000')),
 (12, 4, 2001, Decimal('1021.000000000')),
 (12, 4, 2002, Decimal('1924.000000000')),
 (12, 4, 2003, Decimal('8.000000000')),
 (12, 4, 2004, Decimal('276.000000000')),
 (12, 4, 2005, Decimal('502.000000000')),
 (12, 4, 2006, Decimal('1520.000000000')),
 (12, 4, 2007, Decimal('955.000000000')),
 (12, 4, 2008, Decimal('1750.000000000')),
 (12, 4, 2009, Decimal('812.000000000')),
 (12, 4, 2010, Decimal('782.000000000')),
 (12, 4, 2011, Decimal('574.000000000')),
 (12, 4, 2012, Decimal('118.000000000')),
 (12, 4, 2013, Decimal('167.000000000')),
 (12, 4, 2014, Decimal('94.000000000')),
 (12, 4, 2015, Decimal('275.000000000')),
 (12, 4, 2016, Decimal('274.000000000')),
 (12, 4, 2017, Decimal('1430.000000000')),
 (12, 4, 2018, Decimal('188.000000000')),
 (12, 4, 2019, Decimal('1.000000000')),
 (12, 4, 2020, Decimal('3.000000000')),
 (12, 4, 2021, Decimal('0E-9')),
 (12, 4, 2022, Decimal('0E-9')),
 (12, 6, 1997, Decimal('308.000000000')),
 (12, 6, 1998, Decimal('1349.000000000')),
 (12, 6, 1999, Decimal('5038.000000000')),
 (12, 6, 2000, Decimal('261.000000000')),
 (12, 6, 2001, Decimal('184.000000000')),
 (12, 6, 2002, Decimal('129.000000000')),
 (12, 6, 2003, Decimal('444.000000000')),
 (12, 6, 2004, Decimal('225.000000000')),
 (12, 6, 2005, Decimal('150.000000000')),
 (12, 6, 2006, Decimal('442.000000000')),
 (12, 6, 2007, Decimal('187.000000000')),
 (12, 6, 2008, Decimal('273.000000000')),
 (12, 6, 2009, Decimal('338.000000000')),
 (12, 6, 2010, Decimal('91.000000000')),
 (12, 6, 2011, Decimal('395.000000000')),
 (12, 6, 2012, Decimal('454.000000000')),
 (12, 6, 2013, Decimal('5676.000000000')),
 (12, 6, 2014, Decimal('182.000000000')),
 (12, 6, 2015, Decimal('414.000000000')),
 (12, 6, 2016, Decimal('625.000000000')),
 (12, 6, 2017, Decimal('43.000000000')),
 (12, 6, 2018, Decimal('289.000000000')),
 (12, 6, 2019, Decimal('293.000000000')),
 (12, 6, 2020, Decimal('75.000000000')),
 (12, 6, 2021, Decimal('125.000000000')),
 (12, 6, 2022, Decimal('87.000000000')),
 (12, 7, 1997, Decimal('238.000000000')),
 (12, 7, 1998, Decimal('4441.000000000')),
 (12, 7, 1999, Decimal('38041.000000000')),
 (12, 7, 2000, Decimal('321.000000000')),
 (12, 7, 2001, Decimal('77.000000000')),
 (12, 7, 2002, Decimal('29163.000000000')),
 (12, 7, 2003, Decimal('13272.000000000')),
 (12, 7, 2004, Decimal('1076.000000000')),
 (12, 7, 2005, Decimal('12698.000000000')),
 (12, 7, 2006, Decimal('567.000000000')),
 (12, 7, 2007, Decimal('4221.000000000')),
 (12, 7, 2008, Decimal('9820.000000000')),
 (12, 7, 2009, Decimal('23476.000000000')),
 (12, 7, 2010, Decimal('12643.000000000')),
 (12, 7, 2011, Decimal('9909.000000000')),
 (12, 7, 2012, Decimal('13444.000000000')),
 (12, 7, 2013, Decimal('27846.000000000')),
 (12, 7, 2014, Decimal('12647.000000000')),
 (12, 7, 2015, Decimal('11768.000000000')),
 (12, 7, 2016, Decimal('19908.000000000')),
 (12, 7, 2017, Decimal('14931.000000000')),
 (12, 7, 2018, Decimal('12680.000000000')),
 (12, 7, 2019, Decimal('92.000000000')),
 (12, 7, 2020, Decimal('226.000000000')),
 (12, 7, 2021, Decimal('189.000000000')),
 (12, 7, 2022, Decimal('9.000000000')),
 (12, 9, 1997, Decimal('2094.000000000')),
 (12, 9, 1998, Decimal('3212.000000000')),
 (12, 9, 1999, Decimal('1400.000000000')),
 (12, 9, 2000, Decimal('743.000000000')),
 (12, 9, 2001, Decimal('2992.000000000')),
 (12, 9, 2002, Decimal('1642.000000000')),
 (12, 9, 2003, Decimal('2781.000000000')),
 (12, 9, 2004, Decimal('2964.000000000')),
 (12, 9, 2005, Decimal('1598.000000000')),
 (12, 9, 2006, Decimal('2443.000000000')),
 (12, 9, 2007, Decimal('1291.000000000')),

### Populating Endangerment_of_Animal (TSX data)

There is no year information available for the status in this dataset, but the year is required as it a part of a primary key. We have put a placeholder year 2022 as that is the year of the most recent data in the dataset.

In [130]:
EFFECT_YEAR = 2022

endangerment = tsx[["Scientific Name", "Level"]].copy()
endangerment["Scientific Name"] = endangerment["Scientific Name"].str.strip()

# Checking for conflicting levels
conflicts = endangerment.groupby("Scientific Name")["Level"].nunique()
print("Animals with conflicting levels:", (conflicts > 1).sum())

Animals with conflicting levels: 0

In [131]:
endangerment = endangerment.drop_duplicates("Scientific Name")
endangerment.head()

                  Scientific Name Level
0     amytornis barbatus barbatus    EN
1        amytornis striatus howei    EN
2               antechinus arktos    EN
4               antechinus bellus    VU
5  atrichornis rufescens ferrieri    EN

In [132]:
# Matching animal_ids
animal_ids = pd.read_sql(
    "SELECT animal_id, scientific_name AS `Scientific Name` FROM animal_extinction_db.animal", engine)

endangerment = endangerment.merge(animal_ids, on="Scientific Name", how="left")

# Not matched animals
print("No animal match:", endangerment.loc[endangerment["animal_id"].isna(), "Scientific Name"].unique())

No animal match: <StringArray>
[]
Length: 0, dtype: str

In [133]:
final_end = (
    endangerment.dropna(subset=["animal_id"]) # animals not in the animal table can't satisfy the FK
            .assign(effect_year=EFFECT_YEAR)
            .rename(columns={"Level": "level"})
            [["animal_id", "effect_year", "level"]]
            .astype({"animal_id": int})
)

final_end.to_sql("Endangerment_of_Animal", engine, schema="animal_extinction_db",
                 if_exists="append", index=False)

C:\Users\Latitude\AppData\Local\Temp\ipykernel_29768\2380495385.py:9: UserWarning: The provided table name 'Endangerment_of_Animal' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  final_end.to_sql("Endangerment_of_Animal", engine, schema="animal_extinction_db",

62

In [134]:
%%sql
SELECT *
FROM Endangerment_of_Animal

 * mysql+pymysql://root:***@localhost/animal_extinction_db
62 rows affected.

[(1, 2022, 'EN'),
 (2, 2022, 'EN'),
 (3, 2022, 'EN'),
 (4, 2022, 'VU'),
 (5, 2022, 'EN'),
 (6, 2022, 'EN'),
 (7, 2022, 'VU'),
 (8, 2022, 'EN'),
 (9, 2022, 'EN'),
 (10, 2022, 'EN'),
 (11, 2022, 'VU'),
 (12, 2022, 'VU'),
 (13, 2022, 'CR'),
 (14, 2022, 'VU'),
 (15, 2022, 'VU'),
 (16, 2022, 'EN'),
 (17, 2022, 'EN'),
 (18, 2022, 'VU'),
 (19, 2022, 'EN'),
 (20, 2022, 'EN'),
 (21, 2022, 'VU'),
 (22, 2022, 'VU'),
 (23, 2022, 'VU'),
 (24, 2022, 'EN'),
 (25, 2022, 'CR'),
 (26, 2022, 'EN'),
 (27, 2022, 'CR'),
 (28, 2022, 'EN'),
 (29, 2022, 'EN'),
 (30, 2022, 'CR'),
 (31, 2022, 'EN'),
 (32, 2022, 'EN'),
 (33, 2022, 'EN'),
 (34, 2022, 'EN'),
 (35, 2022, 'EN'),
 (36, 2022, 'EN'),
 (37, 2022, 'VU'),
 (38, 2022, 'VU'),
 (39, 2022, 'CR'),
 (40, 2022, 'CR'),
 (41, 2022, 'EN'),
 (42, 2022, 'EN'),
 (43, 2022, 'EN'),
 (44, 2022, 'VU'),
 (45, 2022, 'EN'),
 (46, 2022, 'EN'),
 (47, 2022, 'CR'),
 (48, 2022, 'VU'),
 (49, 2022, 'VU'),
 (50, 2022, 'EN'),
 (51, 2022, 'CR'),
 (52, 2022, 'VU'),
 (53, 2022, 'EN'),
 (54, 2022, 'VU'),
 (55, 2022, 'VU'),
 (56, 2022, 'EN'),
 (57, 2022, 'EN'),
 (58, 2022, 'VU'),
 (59, 2022, 'VU'),
 (60, 2022, 'EN'),
 (61, 2022, 'EN'),
 (62, 2022, 'VU')]

### Populating Location_Of_Animal  (TSX data)

In [ ]:
tsx_links = (
    tsx[["Scientific Name", "State"]]
    .dropna()
    .drop_duplicates()
)

animal_ids = pd.read_sql(
    "SELECT animal_id, scientific_name FROM animal_extinction_db.animal", engine)
location_ids = pd.read_sql(
    "SELECT location_id, location_name FROM animal_extinction_db.location", engine)

tsx_links = (
    tsx_links.merge(animal_ids, left_on="Scientific Name", right_on="scientific_name", how="left")
             .merge(location_ids, left_on="State", right_on="location_name", how="left")
)

# Checking everything has been matched (yes = all zeros)
print(tsx_links["animal_id"].isna().sum(), tsx_links["location_id"].isna().sum())

0 0

In [136]:
tsx_links = (
    tsx_links[["animal_id", "location_id"]]
    .astype(int)
    .drop_duplicates()
)

with engine.begin() as conn:
    conn.execute(
        text("""INSERT IGNORE INTO animal_extinction_db.Location_Of_Animal (animal_id, location_id)
                VALUES (:animal_id, :location_id)"""),
        tsx_links.to_dict("records"),
    )

In [137]:
%%sql
SELECT *
FROM Location_Of_Animal

 * mysql+pymysql://root:***@localhost/animal_extinction_db
141 rows affected.

[(1, 1),
 (2, 1),
 (3, 1),
 (5, 1),
 (6, 1),
 (10, 1),
 (11, 1),
 (12, 1),
 (13, 1),
 (14, 1),
 (17, 1),
 (18, 1),
 (19, 1),
 (21, 1),
 (31, 1),
 (33, 1),
 (40, 1),
 (41, 1),
 (48, 1),
 (52, 1),
 (55, 1),
 (57, 1),
 (58, 1),
 (4, 2),
 (11, 2),
 (12, 2),
 (13, 2),
 (14, 2),
 (18, 2),
 (19, 2),
 (20, 2),
 (22, 2),
 (23, 2),
 (24, 2),
 (26, 2),
 (31, 2),
 (32, 2),
 (33, 2),
 (36, 2),
 (37, 2),
 (40, 2),
 (57, 2),
 (58, 2),
 (62, 2),
 (9, 3),
 (11, 3),
 (12, 3),
 (13, 3),
 (14, 3),
 (16, 3),
 (18, 3),
 (19, 3),
 (28, 3),
 (31, 3),
 (32, 3),
 (33, 3),
 (39, 3),
 (40, 3),
 (52, 3),
 (53, 3),
 (54, 3),
 (56, 3),
 (57, 3),
 (58, 3),
 (11, 4),
 (12, 4),
 (13, 4),
 (14, 4),
 (18, 4),
 (19, 4),
 (31, 4),
 (33, 4),
 (38, 4),
 (40, 4),
 (57, 4),
 (58, 4),
 (34, 5),
 (49, 5),
 (51, 5),
 (3, 6),
 (6, 6),
 (11, 6),
 (12, 6),
 (13, 6),
 (14, 6),
 (18, 6),
 (19, 6),
 (24, 6),
 (25, 6),
 (31, 6),
 (33, 6),
 (40, 6),
 (44, 6),
 (45, 6),
 (46, 6),
 (50, 6),
 (52, 6),
 (57, 6),
 (58, 6),
 (59, 6),
 (7, 7),
 (8, 7),
 (11, 7),
 (12, 7),
 (13, 7),
 (14, 7),
 (15, 7),
 (18, 7),
 (19, 7),
 (20, 7),
 (29, 7),
 (32, 7),
 (33, 7),
 (35, 7),
 (40, 7),
 (43, 7),
 (47, 7),
 (57, 7),
 (58, 7),
 (60, 7),
 (61, 7),
 (11, 8),
 (42, 8),
 (52, 8),
 (11, 9),
 (12, 9),
 (13, 9),
 (14, 9),
 (18, 9),
 (19, 9),
 (27, 9),
 (28, 9),
 (30, 9),
 (31, 9),
 (33, 9),
 (39, 9),
 (40, 9),
 (42, 9),
 (52, 9),
 (57, 9),
 (58, 9)]

# Inserting EPBC threatened species dataset
Publication date of the data: 28-08-2026

This dataset in available at https://data.gov.au/data/dataset/threatened-species-state-lists under the Creative Commons Attribution 3.0 Australia license.

The dataset contains:

1) 2,222 species, of which 700 are animals and 1,522 plants. Plants are left out in our database as we focus only on animals.

2) Per value the data cointains: scientific name, common name, threatened status, genus, species, subspecies, class, family, and a Yes/- column for each state or territory where it occurs.

In [138]:
tss = pd.read_csv("../Data/Threatened_Species_State_Lists_cleaned.csv", dtype=str, low_memory=False)

In [139]:
tss.columns

Index(['Unnamed: 0', 'Scientific Name', 'Common Name', 'ACT', 'NSW', 'NT',
       'QLD', 'SA', 'TAS', 'VIC', 'WA', 'ACI', 'CKI', 'CI', 'CSI', 'JBT',
       'NFI', 'HMI', 'AAT', 'CMA', 'Kingdom', 'Class', 'Level', 'Year'],
      dtype='str')

### Inserting the states (locations)

In [140]:
%%sql

# Checking what is alredy inserted
SELECT *
FROM location

 * mysql+pymysql://root:***@localhost/animal_extinction_db
9 rows affected.

[(1, 'New South Wales', None, None, None),
 (2, 'Northern Territory', None, None, None),
 (3, 'South Australia', None, None, None),
 (4, 'Tasmania', None, None, None),
 (5, 'Commonwealth', None, None, None),
 (6, 'Queensland', None, None, None),
 (7, 'Western Australia', None, None, None),
 (8, 'Australian Capital Territory', None, None, None),
 (9, 'Victoria', None, None, None)]

In [141]:
state_names = {"ACT": "Australian Capital Territory", "NSW": "New South Wales", "NT": "Northern Territory", "QLD": "Queensland", 
               "SA": "South Australia", "TAS": "Tasmania", "VIC": "Victoria", "WA": "Western Australia", 
               "ACI": "Ashmore and Cartier Islands", "CKI": "Cocos (Keeling) Islands", "CI": "Christmas Island", 
               "CSI": "Coral Sea Islands", "JBT": "Jervis Bay Territory", "NFI": "Norfolk Island", 
               "HMI": "Heard Island and McDonald Islands", "AAT": "Australian Antarctic Territory", "CMA": "Commonwealth Marine Area"}

with engine.begin() as conn:
    conn.execute(
        text("INSERT IGNORE INTO animal_extinction_db.location (location_name) VALUES (:name)"),
        [{"name": name} for name in state_names.values()],
    )

In [142]:
%%sql

# Checking the insertion
SELECT *
FROM location

 * mysql+pymysql://root:***@localhost/animal_extinction_db
18 rows affected.

[(1, 'New South Wales', None, None, None),
 (2, 'Northern Territory', None, None, None),
 (3, 'South Australia', None, None, None),
 (4, 'Tasmania', None, None, None),
 (5, 'Commonwealth', None, None, None),
 (6, 'Queensland', None, None, None),
 (7, 'Western Australia', None, None, None),
 (8, 'Australian Capital Territory', None, None, None),
 (9, 'Victoria', None, None, None),
 (10, 'Ashmore and Cartier Islands', None, None, None),
 (11, 'Cocos (Keeling) Islands', None, None, None),
 (12, 'Christmas Island', None, None, None),
 (13, 'Coral Sea Islands', None, None, None),
 (14, 'Jervis Bay Territory', None, None, None),
 (15, 'Norfolk Island', None, None, None),
 (16, 'Heard Island and McDonald Islands', None, None, None),
 (17, 'Australian Antarctic Territory', None, None, None),
 (18, 'Commonwealth Marine Area', None, None, None)]

### Inserting available Animal data into Animal entity

In [143]:
%%sql

SELECT COUNT(*) AS n_animals
FROM animal;

 * mysql+pymysql://root:***@localhost/animal_extinction_db
1 rows affected.

[(62,)]

In [144]:
# Striping all text columns
str_cols = tss.select_dtypes(include=["object", "string"]).columns
tss[str_cols] = tss[str_cols].apply(lambda s: s.str.strip())


# Putting the scientific name to lowercase
tss["Scientific Name"] = tss["Scientific Name"].str.strip().str.lower()

animals = (
    tss[["Scientific Name", "Common Name", "Class"]]
    .rename(columns={
        "Scientific Name": "scientific_name",
        "Common Name": "common_name",
        "Class": "class",
    })
)

In [145]:
with engine.begin() as conn:
    animals.to_sql("tss_staging", conn, schema="animal_extinction_db",
                   if_exists="replace", index=False)

    conn.execute(text("""
        INSERT IGNORE INTO animal_extinction_db.animal (scientific_name, common_name, animal_class)
        SELECT scientific_name, common_name, `class`
        FROM animal_extinction_db.tss_staging
    """))
    conn.execute(text("DROP TABLE animal_extinction_db.tss_staging"))

In [146]:
%%sql

SELECT COUNT(*) AS n_animals
FROM animal;

 * mysql+pymysql://root:***@localhost/animal_extinction_db
1 rows affected.

[(708,)]

### Populating the Endangerment_of_Animal entity

In [147]:
endangerment = tss[["Scientific Name", "Level", "Year"]].copy()

conflicts = endangerment.groupby(["Scientific Name", "Year"])["Level"].nunique()
print("Animal-years with conflicting levels:", (conflicts > 1).sum())

Animal-years with conflicting levels: 0

In [148]:
bendangerment = endangerment.drop_duplicates("Scientific Name")
endangerment.head()

                  Scientific Name Level  Year
0      acanthiza iredalei rosinae    VU  2026
1        acanthiza lineata whitei    VU  2026
2  acanthiza pusilla magnirostris    EN  2026
3              acanthophis hawkei    VU  2026
4     acanthornis magna greeniana    CR  2026

In [149]:
# Matching animal_ids
animal_ids = pd.read_sql(
    "SELECT animal_id, scientific_name AS `Scientific Name` FROM animal_extinction_db.animal", engine)

endangerment = endangerment.merge(animal_ids, on="Scientific Name", how="left")

# Not matched animals
print("No animal match:", endangerment.loc[endangerment["animal_id"].isna(), "Scientific Name"].unique())

No animal match: <StringArray>
['leucopatus anophthalmus']
Length: 1, dtype: str

In [150]:
final_end = (
    endangerment.dropna(subset=["animal_id"])
        .rename(columns={"Level": "level", "Year": "effect_year"})
        [["animal_id", "effect_year", "level"]]
        .astype({"animal_id": int, "effect_year": int})
        .drop_duplicates(["animal_id", "effect_year"])
)

n_missing = final_end["level"].isna().sum()
final_end = final_end.dropna(subset=["level"])
final_end["level"] = final_end["level"].str.strip().str.upper()

existing = pd.read_sql(
    "SELECT animal_id, effect_year FROM animal_extinction_db.Endangerment_of_Animal", engine
).astype(int)
final_end = (
    final_end.merge(existing, on=["animal_id", "effect_year"], how="left", indicator=True)
             .query("_merge == 'left_only'")
             .drop(columns="_merge")
)

final_end.to_sql("Endangerment_of_Animal", engine, schema="animal_extinction_db",
                 if_exists="append", index=False)

C:\Users\Latitude\AppData\Local\Temp\ipykernel_29768\1099452435.py:22: UserWarning: The provided table name 'Endangerment_of_Animal' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  final_end.to_sql("Endangerment_of_Animal", engine, schema="animal_extinction_db",

698

In [151]:
%%sql
SELECT *
FROM Endangerment_of_Animal

 * mysql+pymysql://root:***@localhost/animal_extinction_db
760 rows affected.

[(1, 2022, 'EN'),
 (1, 2026, 'EN'),
 (2, 2022, 'EN'),
 (2, 2026, 'EN'),
 (3, 2022, 'EN'),
 (3, 2026, 'EN'),
 (4, 2022, 'VU'),
 (4, 2026, 'VU'),
 (5, 2022, 'EN'),
 (6, 2022, 'EN'),
 (7, 2022, 'VU'),
 (7, 2026, 'VU'),
 (8, 2022, 'EN'),
 (8, 2026, 'EN'),
 (9, 2022, 'EN'),
 (9, 2026, 'EN'),
 (10, 2022, 'EN'),
 (10, 2026, 'EN'),
 (11, 2022, 'VU'),
 (11, 2026, 'VU'),
 (12, 2022, 'VU'),
 (12, 2026, 'VU'),
 (13, 2022, 'CR'),
 (13, 2026, 'CR'),
 (14, 2022, 'VU'),
 (14, 2026, 'VU'),
 (15, 2022, 'VU'),
 (15, 2026, 'VU'),
 (16, 2022, 'EN'),
 (16, 2026, 'EN'),
 (17, 2022, 'EN'),
 (17, 2026, 'EN'),
 (18, 2022, 'VU'),
 (18, 2026, 'VU'),
 (19, 2022, 'EN'),
 (19, 2026, 'EN'),
 (20, 2022, 'EN'),
 (21, 2022, 'VU'),
 (21, 2026, 'VU'),
 (22, 2022, 'VU'),
 (22, 2026, 'VU'),
 (23, 2022, 'VU'),
 (24, 2022, 'EN'),
 (24, 2026, 'EN'),
 (25, 2022, 'CR'),
 (25, 2026, 'CR'),
 (26, 2022, 'EN'),
 (26, 2026, 'EN'),
 (27, 2022, 'CR'),
 (27, 2026, 'CR'),
 (28, 2022, 'EN'),
 (28, 2026, 'EN'),
 (29, 2022, 'EN'),
 (30, 2022, 'CR'),
 (30, 2026, 'CR'),
 (31, 2022, 'EN'),
 (31, 2026, 'EN'),
 (32, 2022, 'EN'),
 (32, 2026, 'EN'),
 (33, 2022, 'EN'),
 (33, 2026, 'EN'),
 (34, 2022, 'EN'),
 (34, 2026, 'EN'),
 (35, 2022, 'EN'),
 (35, 2026, 'EN'),
 (36, 2022, 'EN'),
 (36, 2026, 'EN'),
 (37, 2022, 'VU'),
 (37, 2026, 'VU'),
 (38, 2022, 'VU'),
 (38, 2026, 'VU'),
 (39, 2022, 'CR'),
 (39, 2026, 'CR'),
 (40, 2022, 'CR'),
 (40, 2026, 'CR'),
 (41, 2022, 'EN'),
 (41, 2026, 'EN'),
 (42, 2022, 'EN'),
 (42, 2026, 'EN'),
 (43, 2022, 'EN'),
 (43, 2026, 'EN'),
 (44, 2022, 'VU'),
 (44, 2026, 'VU'),
 (45, 2022, 'EN'),
 (46, 2022, 'EN'),
 (46, 2026, 'EN'),
 (47, 2022, 'CR'),
 (47, 2026, 'CR'),
 (48, 2022, 'VU'),
 (48, 2026, 'VU'),
 (49, 2022, 'VU'),
 (49, 2026, 'VU'),
 (50, 2022, 'EN'),
 (50, 2026, 'EN'),
 (51, 2022, 'CR'),
 (51, 2026, 'CR'),
 (52, 2022, 'VU'),
 (52, 2026, 'VU'),
 (53, 2022, 'EN'),
 (54, 2022, 'VU'),
 (54, 2026, 'VU'),
 (55, 2022, 'VU'),
 (55, 2026, 'VU'),
 (56, 2022, 'EN'),
 (56, 2026, 'EN'),
 (57, 2022, 'EN'),
 (57, 2026, 'EN'),
 (58, 2022, 'VU'),
 (58, 2026, 'VU'),
 (59, 2022, 'VU'),
 (59, 2026, 'VU'),
 (60, 2022, 'EN'),
 (61, 2022, 'EN'),
 (62, 2022, 'VU'),
 (62, 2026, 'VU'),
 (64, 2026, 'VU'),
 (65, 2026, 'VU'),
 (66, 2026, 'EN'),
 (67, 2026, 'VU'),
 (68, 2026, 'CR'),
 (69, 2026, 'EN'),
 (70, 2026, 'EN'),
 (71, 2026, 'CR'),
 (72, 2026, 'EN'),
 (73, 2026, 'CR'),
 (74, 2026, 'CR'),
 (75, 2026, 'CR'),
 (76, 2026, 'EN'),
 (77, 2026, 'CR'),
 (78, 2026, 'CR'),
 (79, 2026, 'EN'),
 (80, 2026, 'VU'),
 (81, 2026, 'EN'),
 (82, 2026, 'VU'),
 (83, 2026, 'CR'),
 (84, 2026, 'CR'),
 (85, 2026, 'VU'),
 (86, 2026, 'VU'),
 (87, 2026, 'CR'),
 (88, 2026, 'VU'),
 (89, 2026, 'VU'),
 (90, 2026, 'EN'),
 (91, 2026, 'VU'),
 (92, 2026, 'VU'),
 (93, 2026, 'CR'),
 (94, 2026, 'EN'),
 (95, 2026, 'VU'),
 (96, 2026, 'EX'),
 (97, 2026, 'EN'),
 (98, 2026, 'VU'),
 (99, 2026, 'VU'),
 (100, 2026, 'EN'),
 (101, 2026, 'EN'),
 (102, 2026, 'VU'),
 (103, 2026, 'VU'),
 (104, 2026, 'CR'),
 (105, 2026, 'VU'),
 (106, 2026, 'CR'),
 (107, 2026, 'VU'),
 (108, 2026, 'EN'),
 (109, 2026, 'EN'),
 (110, 2026, 'CR'),
 (111, 2026, 'EN'),
 (112, 2026, 'VU'),
 (113, 2026, 'EN'),
 (114, 2026, 'VU'),
 (115, 2026, 'EN'),
 (116, 2026, 'VU'),
 (117, 2026, 'EN'),
 (118, 2026, 'EX'),
 (119, 2026, 'EX'),
 (120, 2026, 'VU'),
 (121, 2026, 'EX'),
 (122, 2026, 'EX'),
 (123, 2026, 'EX'),
 (124, 2026, 'EN'),
 (125, 2026, 'EN'),
 (126, 2026, 'CR'),
 (127, 2026, 'VU'),
 (128, 2026, 'CR'),
 (129, 2026, 'CR'),
 (130, 2026, 'EN'),
 (131, 2026, 'EN'),
 (132, 2026, 'EN'),
 (133, 2026, 'EX'),
 (134, 2026, 'EN'),
 (135, 2026, 'EN'),
 (136, 2026, 'VU'),
 (137, 2026, 'EN'),
 (138, 2026, 'CR'),
 (139, 2026, 'VU'),
 (140, 2026, 'VU'),
 (141, 2026, 'EN'),
 (142, 2026, 'VU'),
 (143, 2026, 'EN'),
 (144, 2026, 'EN'),
 (145, 2026, 'EN'),
 (146, 2026, 'CR'),
 (147, 2026, 'EN'),
 (148, 2026, 'CD'),
 (149, 2026, 'CD'),
 (150, 2026, 'VU'),
 (151, 2026, 'EN'),
 (152, 2026, 'EX'),
 (153, 2026, 'EX'),
 (154, 2026, 'EN'),
 (155, 2026, 'VU'),
 (156, 2026, 'VU'),
 (157, 2026, 'CR'),
 (158, 2026, 'CR'),
 (159, 2026, 'EN'),
 (160, 2026, 'VU'),
 (161, 2026, 'VU'),
 (162, 2026, 'CR'),
 (163, 2026, 'VU'),
 (164, 2026, 'EX'),
 (165, 2026, 'EX'),
 (166, 2026, 'EX'),
 (167, 2026, 'EN'),
 (168, 2026, 'CR'),
 (169, 2026, 'CR'),
 (170, 2026, 'CR'),
 (171, 2026, 'CR'),
 (172, 2026, 'CR'),
 (173, 2026, 'CR'),
 (174, 2026, 'CR'),
 (175, 2026, 'EN'),
 (176, 2026, 'EN'),
 (177, 2026, 'CR'),
 (178, 2026, 'CR'),
 (179, 2026, 'EN'),
 (180, 2026, 'VU'),
 (181, 2026, 'VU'),
 (182, 2026, 'CR'),
 (183, 2026, 'VU'),
 (184, 2026, 'EN'),
 (185, 2026, 'EX'),
 (186, 2026, 'EX'),
 (187, 2026, 'EN'),
 (188, 2026, 'CR'),
 (189, 2026, 'EN'),
 (190, 2026, 'EN'),
 (191, 2026, 'EX'),
 (192, 2026, 'EN'),
 (193, 2026, 'EN'),
 (194, 2026, 'VU'),
 (195, 2026, 'EN'),
 (196, 2026, 'EN'),
 (197, 2026, 'VU'),
 (198, 2026, 'EN'),
 (199, 2026, 'VU'),
 (200, 2026, 'VU'),
 (201, 2026, 'VU'),
 (202, 2026, 'EN'),
 (203, 2026, 'EN'),
 (204, 2026, 'VU'),
 (205, 2026, 'EN'),
 (206, 2026, 'EN'),
 (207, 2026, 'VU'),
 (208, 2026, 'VU'),
 (209, 2026, 'EN'),
 (210, 2026, 'VU'),
 (211, 2026, 'VU'),
 (212, 2026, 'EN'),
 (213, 2026, 'EX'),
 (214, 2026, 'EX'),
 (215, 2026, 'EX'),
 (216, 2026, 'CR'),
 (217, 2026, 'CR'),
 (218, 2026, 'VU'),
 (219, 2026, 'EN'),
 (220, 2026, 'CR'),
 (221, 2026, 'VU'),
 (222, 2026, 'EN'),
 (223, 2026, 'CR'),
 (224, 2026, 'EX'),
 (225, 2026, 'CR'),
 (226, 2026, 'EN'),
 (227, 2026, 'EN'),
 (228, 2026, 'VU'),
 (229, 2026, 'EN'),
 (230, 2026, 'VU'),
 (231, 2026, 'CR'),
 (232, 2026, 'CR'),
 (233, 2026, 'EN'),
 (234, 2026, 'VU'),
 (235, 2026, 'VU'),
 (236, 2026, 'EN'),
 (237, 2026, 'EN'),
 (238, 2026, 'CR'),
 (239, 2026, 'VU'),
 (240, 2026, 'EN'),
 (241, 2026, 'EN'),
 (242, 2026, 'CR'),
 (243, 2026, 'CR'),
 (244, 2026, 'EN'),
 (245, 2026, 'EN'),
 (246, 2026, 'CR'),
 (247, 2026, 'CR'),
 (248, 2026, 'EN'),
 (249, 2026, 'EN'),
 (250, 2026, 'EN'),
 (251, 2026, 'EN'),
 (252, 2026, 'EN'),
 (253, 2026, 'EN'),
 (254, 2026, 'CR'),
 (255, 2026, 'CR'),
 (256, 2026, 'EN'),
 (257, 2026, 'CR'),
 (258, 2026, 'CR'),
 (259, 2026, 'EN'),
 (260, 2026, 'CR'),
 (261, 2026, 'EN'),
 (262, 2026, 'EN'),
 (263, 2026, 'CR'),
 (264, 2026, 'EN'),
 (265, 2026, 'EN'),
 (266, 2026, 'EN'),
 (267, 2026, 'EN'),
 (268, 2026, 'EN'),
 (269, 2026, 'EN'),
 (270, 2026, 'EN'),
 (271, 2026, 'EN'),
 (272, 2026, 'CR'),
 (273, 2026, 'CR'),
 (274, 2026, 'EN'),
 (275, 2026, 'VU'),
 (276, 2026, 'EN'),
 (277, 2026, 'EN'),
 (278, 2026, 'VU'),
 (279, 2026, 'VU'),
 (280, 2026, 'EN'),
 (281, 2026, 'VU'),
 (282, 2026, 'VU'),
 (283, 2026, 'EN'),
 (284, 2026, 'CR'),
 (285, 2026, 'EN'),
 (286, 2026, 'CR'),
 (287, 2026, 'EN'),
 (288, 2026, 'EN'),
 (289, 2026, 'CR'),
 (290, 2026, 'EN'),
 (291, 2026, 'CR'),
 (292, 2026, 'CR'),
 (293, 2026, 'CR'),
 (294, 2026, 'CR'),
 (295, 2026, 'VU'),
 (297, 2026, 'CR'),
 (298, 2026, 'CR'),
 (299, 2026, 'CR'),
 (300, 2026, 'CR'),
 (301, 2026, 'CR'),
 (302, 2026, 'CR'),
 (303, 2026, 'CR'),
 (304, 2026, 'VU'),
 (305, 2026, 'EN'),
 (306, 2026, 'EN'),
 (307, 2026, 'VU'),
 (308, 2026, 'EN'),
 (309, 2026, 'EN'),
 (310, 2026, 'VU'),
 (311, 2026, 'CD'),
 (312, 2026, 'VU'),
 (313, 2026, 'CR'),
 (314, 2026, 'VU'),
 (315, 2026, 'VU'),
 (316, 2026, 'VU'),
 (317, 2026, 'VU'),
 (318, 2026, 'EX'),
 (319, 2026, 'EN'),
 (320, 2026, 'CR'),
 (321, 2026, 'VU'),
 (322, 2026, 'CR'),
 (323, 2026, 'CR'),
 (324, 2026, 'VU'),
 (325, 2026, 'VU'),
 (326, 2026, 'EN'),
 (327, 2026, 'EN'),
 (328, 2026, 'EN'),
 (329, 2026, 'EN'),
 (330, 2026, 'EX'),
 (331, 2026, 'CR'),
 (332, 2026, 'EN'),
 (333, 2026, 'EN'),
 (334, 2026, 'VU'),
 (335, 2026, 'VU'),
 (336, 2026, 'EN'),
 (337, 2026, 'CR'),
 (338, 2026, 'VU'),
 (339, 2026, 'VU'),
 (340, 2026, 'CD'),
 (341, 2026, 'VU'),
 (342, 2026, 'CR'),
 (343, 2026, 'EX'),
 (344, 2026, 'EN'),
 (345, 2026, 'EX'),
 (346, 2026, 'EN'),
 (347, 2026, 'CR'),
 (348, 2026, 'CR'),
 (349, 2026, 'VU'),
 (350, 2026, 'VU'),
 (351, 2026, 'VU'),
 (352, 2026, 'VU'),
 (353, 2026, 'EN'),
 (354, 2026, 'VU'),
 (355, 2026, 'EX'),
 (356, 2026, 'VU'),
 (357, 2026, 'VU'),
 (358, 2026, 'EN'),
 (359, 2026, 'VU'),
 (360, 2026, 'EX'),
 (361, 2026, 'EX'),
 (362, 2026, 'EX'),
 (363, 2026, 'VU'),
 (364, 2026, 'EX'),
 (365, 2026, 'EN'),
 (366, 2026, 'CR'),
 (367, 2026, 'CR'),
 (368, 2026, 'CR'),
 (369, 2026, 'CR'),
 (370, 2026, 'VU'),
 (371, 2026, 'EN'),
 (372, 2026, 'CR'),
 (373, 2026, 'EX'),
 (374, 2026, 'VU'),
 (375, 2026, 'EN'),
 (376, 2026, 'EN'),
 (377, 2026, 'EN'),
 (378, 2026, 'EN'),
 (379, 2026, 'VU'),
 (380, 2026, 'VU'),
 (381, 2026, 'VU'),
 (382, 2026, 'EX'),
 (383, 2026, 'VU'),
 (384, 2026, 'VU'),
 (385, 2026, 'EN'),
 (386, 2026, 'VU'),
 (387, 2026, 'EN'),
 (388, 2026, 'VU'),
 (389, 2026, 'EN'),
 (390, 2026, 'EN'),
 (391, 2026, 'EN'),
 (392, 2026, 'VU'),
 (393, 2026, 'EN'),
 (394, 2026, 'CR'),
 (395, 2026, 'VU'),
 (396, 2026, 'VU'),
 (397, 2026, 'CR'),
 (398, 2026, 'EN'),
 (399, 2026, 'CR'),
 (400, 2026, 'CR'),
 (401, 2026, 'CR'),
 (402, 2026, 'VU'),
 (403, 2026, 'VU'),
 (404, 2026, 'VU'),
 (405, 2026, 'CR'),
 (406, 2026, 'VU'),
 (407, 2026, 'VU'),
 (408, 2026, 'EN'),
 (409, 2026, 'EN'),
 (410, 2026, 'EN'),
 (411, 2026, 'EN'),
 (412, 2026, 'EN'),
 (413, 2026, 'EN'),
 (414, 2026, 'VU'),
 (415, 2026, 'EN'),
 (416, 2026, 'VU'),
 (417, 2026, 'VU'),
 (418, 2026, 'VU'),
 (419, 2026, 'EX'),
 (420, 2026, 'VU'),
 (421, 2026, 'VU'),
 (422, 2026, 'EN'),
 (423, 2026, 'CR'),
 (424, 2026, 'EN'),
 (425, 2026, 'CR'),
 (426, 2026, 'CR'),
 (427, 2026, 'CR'),
 (428, 2026, 'VU'),
 (429, 2026, 'EN'),
 (430, 2026, 'CR'),
 (431, 2026, 'EN'),
 (432, 2026, 'CR'),
 (433, 2026, 'CR'),
 (434, 2026, 'EN'),
 (435, 2026, 'EX'),
 (436, 2026, 'EN'),
 (437, 2026, 'VU'),
 (438, 2026, 'EN'),
 (439, 2026, 'CR'),
 (440, 2026, 'EN'),
 (441, 2026, 'VU'),
 (442, 2026, 'CR'),
 (443, 2026, 'VU'),
 (444, 2026, 'VU'),
 (445, 2026, 'EN'),
 (446, 2026, 'VU'),
 (447, 2026, 'EN'),
 (448, 2026, 'EN'),
 (449, 2026, 'EN'),
 (450, 2026, 'CR'),
 (451, 2026, 'EN'),
 (452, 2026, 'EN'),
 (453, 2026, 'CR'),
 (454, 2026, 'EN'),
 (455, 2026, 'EN'),
 (456, 2026, 'CR'),
 (457, 2026, 'VU'),
 (458, 2026, 'VU'),
 (459, 2026, 'EN'),
 (460, 2026, 'EN'),
 (461, 2026, 'EN'),
 (462, 2026, 'VU'),
 (463, 2026, 'VU'),
 (464, 2026, 'VU'),
 (465, 2026, 'EN'),
 (466, 2026, 'EN'),
 (467, 2026, 'CR'),
 (468, 2026, 'VU'),
 (469, 2026, 'EN'),
 (470, 2026, 'CR'),
 (471, 2026, 'EN'),
 (472, 2026, 'EX'),
 (473, 2026, 'VU'),
 (474, 2026, 'EX'),
 (475, 2026, 'EN'),
 (476, 2026, 'EX'),
 (477, 2026, 'VU'),
 (478, 2026, 'VU'),
 (479, 2026, 'EX'),
 (480, 2026, 'EN'),
 (481, 2026, 'VU'),
 (482, 2026, 'EX'),
 (483, 2026, 'EX'),
 (484, 2026, 'EX'),
 (485, 2026, 'EX'),
 (486, 2026, 'CR'),
 (487, 2026, 'VU'),
 (488, 2026, 'VU'),
 (489, 2026, 'EX'),
 (490, 2026, 'CR'),
 (491, 2026, 'CR'),
 (492, 2026, 'VU'),
 (493, 2026, 'EX'),
 (494, 2026, 'VU'),
 (495, 2026, 'VU'),
 (496, 2026, 'VU'),
 (497, 2026, 'CR'),
 (498, 2026, 'VU'),
 (499, 2026, 'EN'),
 (500, 2026, 'CR'),
 (501, 2026, 'VU'),
 (502, 2026, 'VU'),
 (503, 2026, 'VU'),
 (504, 2026, 'VU'),
 (505, 2026, 'EN'),
 (506, 2026, 'VU'),
 (507, 2026, 'VU'),
 (508, 2026, 'EN'),
 (509, 2026, 'EN'),
 (510, 2026, 'VU'),
 (511, 2026, 'EN'),
 (512, 2026, 'EN'),
 (513, 2026, 'VU'),
 (514, 2026, 'CR'),
 (515, 2026, 'EN'),
 (516, 2026, 'EX'),
 (517, 2026, 'EX'),
 (518, 2026, 'VU'),
 (519, 2026, 'EN'),
 (520, 2026, 'EX'),
 (521, 2026, 'EX'),
 (522, 2026, 'EX'),
 (523, 2026, 'CR'),
 (524, 2026, 'VU'),
 (525, 2026, 'VU'),
 (526, 2026, 'EN'),
 (527, 2026, 'EN'),
 (528, 2026, 'EN'),
 (529, 2026, 'EN'),
 (530, 2026, 'CR'),
 (531, 2026, 'EN'),
 (532, 2026, 'VU'),
 (533, 2026, 'VU'),
 (534, 2026, 'EN'),
 (535, 2026, 'VU'),
 (536, 2026, 'EN'),
 (537, 2026, 'VU'),
 (538, 2026, 'VU'),
 (539, 2026, 'VU'),
 (540, 2026, 'CR'),
 (541, 2026, 'CR'),
 (542, 2026, 'EN'),
 (543, 2026, 'EN'),
 (544, 2026, 'VU'),
 (545, 2026, 'VU'),
 (546, 2026, 'VU'),
 (547, 2026, 'EN'),
 (548, 2026, 'CR'),
 (549, 2026, 'EN'),
 (550, 2026, 'EN'),
 (551, 2026, 'EN'),
 (552, 2026, 'EN'),
 (553, 2026, 'VU'),
 (554, 2026, 'VU'),
 (555, 2026, 'EN'),
 (556, 2026, 'EN'),
 (557, 2026, 'CR'),
 (558, 2026, 'CR'),
 (559, 2026, 'CR'),
 (560, 2026, 'EX'),
 (561, 2026, 'EN'),
 (562, 2026, 'VU'),
 (563, 2026, 'VU'),
 (564, 2026, 'VU'),
 (565, 2026, 'VU'),
 (566, 2026, 'VU'),
 (567, 2026, 'VU'),
 (568, 2026, 'EN'),
 (569, 2026, 'EX'),
 (570, 2026, 'CR'),
 (571, 2026, 'EN'),
 (572, 2026, 'EX'),
 (573, 2026, 'VU'),
 (574, 2026, 'VU'),
 (575, 2026, 'VU'),
 (576, 2026, 'EN'),
 (577, 2026, 'VU'),
 (578, 2026, 'EN'),
 (579, 2026, 'CR'),
 (580, 2026, 'VU'),
 (581, 2026, 'EN'),
 (582, 2026, 'EX'),
 (583, 2026, 'EN'),
 (584, 2026, 'VU'),
 (585, 2026, 'CR'),
 (586, 2026, 'CR'),
 (587, 2026, 'CR'),
 (588, 2026, 'CR'),
 (589, 2026, 'EN'),
 (590, 2026, 'EX'),
 (591, 2026, 'VU'),
 (592, 2026, 'VU'),
 (593, 2026, 'EN'),
 (594, 2026, 'EX'),
 (595, 2026, 'EX'),
 (596, 2026, 'EN'),
 (597, 2026, 'VU'),
 (598, 2026, 'EN'),
 (599, 2026, 'CR'),
 (600, 2026, 'VU'),
 (601, 2026, 'CR'),
 (602, 2026, 'EN'),
 (603, 2026, 'EN'),
 (604, 2026, 'EN'),
 (605, 2026, 'CR'),
 (606, 2026, 'EN'),
 (607, 2026, 'VU'),
 (608, 2026, 'EX'),
 (609, 2026, 'VU'),
 (610, 2026, 'CR'),
 (611, 2026, 'VU'),
 (612, 2026, 'EX'),
 (613, 2026, 'EX'),
 (614, 2026, 'CD'),
 (615, 2026, 'EX'),
 (616, 2026, 'EX'),
 (617, 2026, 'EN'),
 (618, 2026, 'VU'),
 (619, 2026, 'VU'),
 (620, 2026, 'VU'),
 (621, 2026, 'EX'),
 (622, 2026, 'CR'),
 (623, 2026, 'EN'),
 (624, 2026, 'VU'),
 (625, 2026, 'CR'),
 (626, 2026, 'EN'),
 (627, 2026, 'EN'),
 (628, 2026, 'EN'),
 (629, 2026, 'EN'),
 (630, 2026, 'EN'),
 (631, 2026, 'EN'),
 (632, 2026, 'CD'),
 (633, 2026, 'VU'),
 (634, 2026, 'EN'),
 (635, 2026, 'VU'),
 (636, 2026, 'VU'),
 (637, 2026, 'EN'),
 (638, 2026, 'EN'),
 (639, 2026, 'VU'),
 (640, 2026, 'CD'),
 (641, 2026, 'VU'),
 (642, 2026, 'EN'),
 (643, 2026, 'VU'),
 (644, 2026, 'EN'),
 (645, 2026, 'VU'),
 (646, 2026, 'VU'),
 (647, 2026, 'CR'),
 (648, 2026, 'EN'),
 (649, 2026, 'EN'),
 (650, 2026, 'EN'),
 (651, 2026, 'EN'),
 (652, 2026, 'VU'),
 (653, 2026, 'VU'),
 (654, 2026, 'EN'),
 (655, 2026, 'VU'),
 (656, 2026, 'EX'),
 (657, 2026, 'EX'),
 (658, 2026, 'EN'),
 (659, 2026, 'CR'),
 (660, 2026, 'CR'),
 (661, 2026, 'VU'),
 (662, 2026, 'VU'),
 (663, 2026, 'VU'),
 (664, 2026, 'EN'),
 (665, 2026, 'EN'),
 (666, 2026, 'EN'),
 (667, 2026, 'VU'),
 (668, 2026, 'VU'),
 (669, 2026, 'VU'),
 (670, 2026, 'VU'),
 (671, 2026, 'EN'),
 (672, 2026, 'CR'),
 (673, 2026, 'VU'),
 (674, 2026, 'EX'),
 (675, 2026, 'CR'),
 (676, 2026, 'EN'),
 (677, 2026, 'CR'),
 (678, 2026, 'VU'),
 (679, 2026, 'EN'),
 (680, 2026, 'EN'),
 (681, 2026, 'EN'),
 (682, 2026, 'EX'),
 (683, 2026, 'EX'),
 (684, 2026, 'VU'),
 (685, 2026, 'CR'),
 (686, 2026, 'EN'),
 (687, 2026, 'EN'),
 (688, 2026, 'CR'),
 (689, 2026, 'CR'),
 (690, 2026, 'EN'),
 (691, 2026, 'CR'),
 (692, 2026, 'VU'),
 (693, 2026, 'VU'),
 (694, 2026, 'EN'),
 (695, 2026, 'VU'),
 (696, 2026, 'EN'),
 (697, 2026, 'EN'),
 (698, 2026, 'VU'),
 (699, 2026, 'EN'),
 (700, 2026, 'CR'),
 (701, 2026, 'VU'),
 (702, 2026, 'CR'),
 (703, 2026, 'EN'),
 (704, 2026, 'CR'),
 (705, 2026, 'EN'),
 (706, 2026, 'EX'),
 (707, 2026, 'EX'),
 (708, 2026, 'EN'),
 (709, 2026, 'CR')]

### Populating Location_Of_Animal

In [ ]:
state_cols = list(state_names.keys())  

tss_links = tss.melt(
    id_vars=["Scientific Name"],
    value_vars=state_cols,
    var_name="state_code",
    value_name="present",
)

# Keeping only the states where the animal occurs ("Yes")
tss_links = tss_links[tss_links["present"].astype(str).str.strip().str.lower() == "yes"].copy()
tss_links["location_name"] = tss_links["state_code"].map(state_names)

animal_ids = pd.read_sql(
    "SELECT animal_id, scientific_name FROM animal_extinction_db.animal", engine)
location_ids = pd.read_sql(
    "SELECT location_id, location_name FROM animal_extinction_db.location", engine)

tss_links = (
    tss_links.merge(animal_ids, left_on="Scientific Name", right_on="scientific_name", how="left")
             .merge(location_ids, on="location_name", how="left")
)

# Checking everything has been matched
print(tss_links["animal_id"].isna().sum(), tss_links["location_id"].isna().sum())

1 0

In [153]:
tss_links = (
    tss_links.dropna(subset=["animal_id", "location_id"])
             [["animal_id", "location_id"]]
             .astype({"animal_id": int, "location_id": int})
             .drop_duplicates()
)


existing = pd.read_sql(
    "SELECT animal_id, location_id FROM animal_extinction_db.Location_Of_Animal", engine
).astype(int)
tss_links = (
    tss_links.merge(existing, on=["animal_id", "location_id"], how="left", indicator=True)
             .query("_merge == 'left_only'")
             .drop(columns="_merge")
)


tss_links.to_sql("Location_Of_Animal", engine, schema="animal_extinction_db",
                 if_exists="append", index=False)

C:\Users\Latitude\AppData\Local\Temp\ipykernel_29768\454181563.py:19: UserWarning: The provided table name 'Location_Of_Animal' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  tss_links.to_sql("Location_Of_Animal", engine, schema="animal_extinction_db",

1623

In [154]:
%%sql
SELECT *
FROM Location_Of_Animal

 * mysql+pymysql://root:***@localhost/animal_extinction_db
1764 rows affected.

[(1, 1),
 (2, 1),
 (3, 1),
 (5, 1),
 (6, 1),
 (7, 1),
 (8, 1),
 (9, 1),
 (10, 1),
 (11, 1),
 (12, 1),
 (13, 1),
 (14, 1),
 (17, 1),
 (18, 1),
 (19, 1),
 (21, 1),
 (27, 1),
 (28, 1),
 (31, 1),
 (33, 1),
 (34, 1),
 (39, 1),
 (40, 1),
 (41, 1),
 (42, 1),
 (46, 1),
 (48, 1),
 (49, 1),
 (52, 1),
 (54, 1),
 (55, 1),
 (57, 1),
 (58, 1),
 (59, 1),
 (78, 1),
 (82, 1),
 (83, 1),
 (84, 1),
 (88, 1),
 (93, 1),
 (95, 1),
 (96, 1),
 (98, 1),
 (102, 1),
 (103, 1),
 (104, 1),
 (105, 1),
 (106, 1),
 (109, 1),
 (111, 1),
 (112, 1),
 (113, 1),
 (114, 1),
 (119, 1),
 (121, 1),
 (122, 1),
 (124, 1),
 (125, 1),
 (132, 1),
 (136, 1),
 (138, 1),
 (140, 1),
 (141, 1),
 (149, 1),
 (152, 1),
 (155, 1),
 (161, 1),
 (163, 1),
 (164, 1),
 (165, 1),
 (173, 1),
 (175, 1),
 (176, 1),
 (186, 1),
 (187, 1),
 (188, 1),
 (190, 1),
 (194, 1),
 (196, 1),
 (198, 1),
 (199, 1),
 (202, 1),
 (203, 1),
 (205, 1),
 (207, 1),
 (208, 1),
 (210, 1),
 (211, 1),
 (212, 1),
 (216, 1),
 (217, 1),
 (234, 1),
 (235, 1),
 (236, 1),
 (238, 1),
 (239, 1),
 (241, 1),
 (245, 1),
 (246, 1),
 (247, 1),
 (251, 1),
 (252, 1),
 (253, 1),
 (254, 1),
 (255, 1),
 (257, 1),
 (259, 1),
 (261, 1),
 (263, 1),
 (264, 1),
 (265, 1),
 (267, 1),
 (269, 1),
 (270, 1),
 (272, 1),
 (274, 1),
 (275, 1),
 (276, 1),
 (278, 1),
 (281, 1),
 (282, 1),
 (286, 1),
 (297, 1),
 (298, 1),
 (302, 1),
 (303, 1),
 (305, 1),
 (311, 1),
 (312, 1),
 (315, 1),
 (318, 1),
 (321, 1),
 (322, 1),
 (323, 1),
 (324, 1),
 (325, 1),
 (326, 1),
 (327, 1),
 (328, 1),
 (332, 1),
 (335, 1),
 (336, 1),
 (340, 1),
 (346, 1),
 (347, 1),
 (350, 1),
 (353, 1),
 (361, 1),
 (366, 1),
 (367, 1),
 (368, 1),
 (370, 1),
 (371, 1),
 (373, 1),
 (374, 1),
 (384, 1),
 (385, 1),
 (387, 1),
 (390, 1),
 (392, 1),
 (393, 1),
 (394, 1),
 (395, 1),
 (398, 1),
 (402, 1),
 (403, 1),
 (404, 1),
 (405, 1),
 (406, 1),
 (407, 1),
 (408, 1),
 (409, 1),
 (411, 1),
 (412, 1),
 (414, 1),
 (415, 1),
 (417, 1),
 (418, 1),
 (422, 1),
 (424, 1),
 (429, 1),
 (436, 1),
 (444, 1),
 (445, 1),
 (446, 1),
 (448, 1),
 (451, 1),
 (452, 1),
 (453, 1),
 (454, 1),
 (455, 1),
 (458, 1),
 (460, 1),
 (463, 1),
 (466, 1),
 (468, 1),
 (474, 1),
 (477, 1),
 (481, 1),
 (482, 1),
 (484, 1),
 (486, 1),
 (488, 1),
 (489, 1),
 (492, 1),
 (493, 1),
 (503, 1),
 (504, 1),
 (510, 1),
 (514, 1),
 (515, 1),
 (516, 1),
 (523, 1),
 (525, 1),
 (535, 1),
 (538, 1),
 (541, 1),
 (544, 1),
 (547, 1),
 (549, 1),
 (550, 1),
 (551, 1),
 (552, 1),
 (553, 1),
 (554, 1),
 (555, 1),
 (561, 1),
 (564, 1),
 (566, 1),
 (567, 1),
 (568, 1),
 (569, 1),
 (571, 1),
 (573, 1),
 (574, 1),
 (577, 1),
 (579, 1),
 (580, 1),
 (582, 1),
 (583, 1),
 (584, 1),
 (586, 1),
 (587, 1),
 (591, 1),
 (593, 1),
 (594, 1),
 (595, 1),
 (596, 1),
 (597, 1),
 (599, 1),
 (601, 1),
 (605, 1),
 (606, 1),
 (609, 1),
 (614, 1),
 (618, 1),
 (621, 1),
 (623, 1),
 (626, 1),
 (627, 1),
 (628, 1),
 (632, 1),
 (639, 1),
 (640, 1),
 (643, 1),
 (646, 1),
 (655, 1),
 (661, 1),
 (662, 1),
 (664, 1),
 (665, 1),
 (666, 1),
 (667, 1),
 (668, 1),
 (669, 1),
 (670, 1),
 (672, 1),
 (673, 1),
 (683, 1),
 (684, 1),
 (688, 1),
 (689, 1),
 (690, 1),
 (696, 1),
 (697, 1),
 (698, 1),
 (702, 1),
 (707, 1),
 (4, 2),
 (11, 2),
 (12, 2),
 (13, 2),
 (14, 2),
 (18, 2),
 (19, 2),
 (20, 2),
 (22, 2),
 (23, 2),
 (24, 2),
 (26, 2),
 (31, 2),
 (32, 2),
 (33, 2),
 (35, 2),
 (36, 2),
 (37, 2),
 (40, 2),
 (57, 2),
 (58, 2),
 (59, 2),
 (62, 2),
 (67, 2),
 (79, 2),
 (82, 2),
 (86, 2),
 (95, 2),
 (103, 2),
 (113, 2),
 (115, 2),
 (118, 2),
 (121, 2),
 (122, 2),
 (140, 2),
 (141, 2),
 (142, 2),
 (152, 2),
 (153, 2),
 (155, 2),
 (179, 2),
 (193, 2),
 (194, 2),
 (205, 2),
 (222, 2),
 (235, 2),
 (236, 2),
 (237, 2),
 (278, 2),
 (279, 2),
 (317, 2),
 (319, 2),
 (320, 2),
 (321, 2),
 (333, 2),
 (350, 2),
 (355, 2),
 (358, 2),
 (370, 2),
 (371, 2),
 (373, 2),
 (384, 2),
 (386, 2),
 (389, 2),
 (410, 2),
 (416, 2),
 (418, 2),
 (419, 2),
 (430, 2),
 (438, 2),
 (443, 2),
 (452, 2),
 (463, 2),
 (468, 2),
 (479, 2),
 (480, 2),
 (481, 2),
 (482, 2),
 (487, 2),
 (493, 2),
 (494, 2),
 (496, 2),
 (497, 2),
 (514, 2),
 (517, 2),
 (529, 2),
 (530, 2),
 (532, 2),
 (541, 2),
 (544, 2),
 (545, 2),
 (564, 2),
 (565, 2),
 (575, 2),
 (576, 2),
 (577, 2),
 (591, 2),
 (592, 2),
 (618, 2),
 (623, 2),
 (624, 2),
 (631, 2),
 (634, 2),
 (635, 2),
 (638, 2),
 (639, 2),
 (640, 2),
 (646, 2),
 (653, 2),
 (677, 2),
 (678, 2),
 (693, 2),
 (694, 2),
 (695, 2),
 (699, 2),
 (700, 2),
 (708, 2),
 (709, 2),
 (1, 3),
 (2, 3),
 (7, 3),
 (8, 3),
 (9, 3),
 (11, 3),
 (12, 3),
 (13, 3),
 (14, 3),
 (16, 3),
 (18, 3),
 (19, 3),
 (28, 3),
 (31, 3),
 (32, 3),
 (33, 3),
 (34, 3),
 (38, 3),
 (39, 3),
 (40, 3),
 (41, 3),
 (52, 3),
 (53, 3),
 (54, 3),
 (56, 3),
 (57, 3),
 (58, 3),
 (64, 3),
 (65, 3),
 (80, 3),
 (81, 3),
 (82, 3),
 (85, 3),
 (91, 3),
 (92, 3),
 (93, 3),
 (95, 3),
 (97, 3),
 (99, 3),
 (102, 3),
 (103, 3),
 (112, 3),
 (113, 3),
 (114, 3),
 (119, 3),
 (121, 3),
 (122, 3),
 (123, 3),
 (125, 3),
 (131, 3),
 (132, 3),
 (133, 3),
 (134, 3),
 (140, 3),
 (141, 3),
 (149, 3),
 (152, 3),
 (153, 3),
 (155, 3),
 (158, 3),
 (162, 3),
 (165, 3),
 (174, 3),
 (175, 3),
 (193, 3),
 (194, 3),
 (196, 3),
 (198, 3),
 (199, 3),
 (205, 3),
 (207, 3),
 (209, 3),
 (210, 3),
 (211, 3),
 (212, 3),
 (214, 3),
 (244, 3),
 (274, 3),
 (278, 3),
 (297, 3),
 (310, 3),
 (311, 3),
 (312, 3),
 (321, 3),
 (324, 3),
 (335, 3),
 (341, 3),
 (350, 3),
 (352, 3),
 (358, 3),
 (361, 3),
 (368, 3),
 (370, 3),
 (373, 3),
 (374, 3),
 (386, 3),
 (390, 3),
 (404, 3),
 (409, 3),
 (412, 3),
 (414, 3),
 (415, 3),
 (416, 3),
 (417, 3),
 (418, 3),
 (419, 3),
 (422, 3),
 (424, 3),
 (429, 3),
 (434, 3),
 (442, 3),
 (447, 3),
 (448, 3),
 (449, 3),
 (450, 3),
 (452, 3),
 (458, 3),
 (459, 3),
 (462, 3),
 (465, 3),
 (468, 3),
 (469, 3),
 (470, 3),
 (471, 3),
 (476, 3),
 (478, 3),
 (479, 3),
 (481, 3),
 (482, 3),
 (485, 3),
 (488, 3),
 (493, 3),
 (494, 3),
 (503, 3),
 (504, 3),
 (514, 3),
 (515, 3),
 (517, 3),
 (519, 3),
 (521, 3),
 (522, 3),
 (532, 3),
 (538, 3),
 (541, 3),
 (544, 3),
 (554, 3),
 (563, 3),
 (564, 3),
 (565, 3),
 (566, 3),
 (574, 3),
 (580, 3),
 (584, 3),
 (590, 3),
 (591, 3),
 (592, 3),
 (593, 3),
 (595, 3),
 (598, 3),
 (602, 3),
 (603, 3),
 (606, 3),
 (607, 3),
 (618, 3),
 (623, 3),
 (632, 3),
 (637, 3),
 (638, 3),
 (642, 3),
 (643, 3),
 (646, 3),
 (648, 3),
 (649, 3),
 (650, 3),
 (651, 3),
 (655, 3),
 (661, 3),
 (662, 3),
 (663, 3),
 (664, 3),
 (665, 3),
 (667, 3),
 (668, 3),
 (669, 3),
 (670, 3),
 (673, 3),
 (676, 3),
 (704, 3),
 (705, 3),
 (9, 4),
 (11, 4),
 (12, 4),
 (13, 4),
 (14, 4),
 (18, 4),
 (19, 4),
 (31, 4),
 (33, 4),
 (34, 4),
 (38, 4),
 (39, 4),
 (40, 4),
 (48, 4),
 (54, 4),
 (57, 4),
 (58, 4),
 (66, 4),
 (68, 4),
 (77, 4),
 (94, 4),
 (100, 4),
 (101, 4),
 (102, 4),
 (103, 4),
 (107, 4),
 (112, 4),
 (113, 4),
 (114, 4),
 (126, 4),
 (127, 4),
 (132, 4),
 (140, 4),
 (141, 4),
 (143, 4),
 (144, 4),
 (145, 4),
 (146, 4),
 (149, 4),
 (151, 4),
 (155, 4),
 (185, 4),
 (197, 4),
 (198, 4),
 (205, 4),
 (207, 4),
 (208, 4),
 (210, 4),
 (211, 4),
 (212, 4),
 (213, 4),
 (215, 4),
 (226, 4),
 (227, 4),
 (228, 4),
 (229, 4),
 (230, 4),
 (274, 4),
 (281, 4),
 (285, 4),
 (287, 4),
 (290, 4),
 (295, 4),
 (296, 4),
 (304, 4),
 (309, 4),
 (311, 4),
 (312, 4),
 (324, 4),
 (335, 4),
 (337, 4),
 (338, 4),
 (339, 4),
 (340, 4),
 (343, 4),
 (345, 4),
 (368, 4),
 (381, 4),
 (391, 4),
 (404, 4),
 (417, 4),
 (423, 4),
 (439, 4),
 (465, 4),
 (468, 4),
 (498, 4),
 (499, 4),
 (504, 4),
 (506, 4),
 (507, 4),
 (508, 4),
 (512, 4),
 (513, 4),
 (518, 4),
 (554, 4),
 (562, 4),
 (564, 4),
 (580, 4),
 (584, 4),
 (606, 4),
 (607, 4),
 (614, 4),
 (618, 4),
 (629, 4),
 (632, 4),
 (644, 4),
 (646, 4),
 (652, 4),
 (661, 4),
 (662, 4),
 (663, 4),
 (664, 4),
 (665, 4),
 (666, 4),
 (667, 4),
 (668, 4),
 (669, 4),
 (670, 4),
 (673, 4),
 (674, 4),
 (675, 4),
 (692, 4),
 (703, 4),
 (34, 5),
 (49, 5),
 (51, 5),
 (1, 6),
 (3, 6),
 (6, 6),
 (9, 6),
 (11, 6),
 (12, 6),
 (13, 6),
 (14, 6),
 (17, 6),
 (18, 6),
 (19, 6),
 (21, 6),
 (22, 6),
 (24, 6),
 (25, 6),
 (31, 6),
 (32, 6),
 (33, 6),
 (34, 6),
 (40, 6),
 (41, 6),
 (42, 6),
 (44, 6),
 (45, 6),
 (46, 6),
 (48, 6),
 (49, 6),
 (50, 6),
 (52, 6),
 (57, 6),
 (58, 6),
 (59, 6),
 (67, 6),
 (70, 6),
 (71, 6),
 (72, 6),
 (79, 6),
 (87, 6),
 (88, 6),
 (90, 6),
 (93, 6),
 (95, 6),
 (102, 6),
 (103, 6),
 (104, 6),
 (105, 6),
 (109, 6),
 (110, 6),
 (112, 6),
 (113, 6),
 (114, 6),
 (119, 6),
 (121, 6),
 (122, 6),
 (124, 6),
 (125, 6),
 (129, 6),
 (130, 6),
 (133, 6),
 (136, 6),
 (138, 6),
 (140, 6),
 (141, 6),
 (147, 6),
 (152, 6),
 (153, 6),
 (155, 6),
 (156, 6),
 (159, 6),
 (160, 6),
 (163, 6),
 (165, 6),
 (166, 6),
 (167, 6),
 (168, 6),
 (169, 6),
 (170, 6),
 (171, 6),
 (172, 6),
 (182, 6),
 (188, 6),
 (190, 6),
 (193, 6),
 (194, 6),
 (195, 6),
 (196, 6),
 (200, 6),
 (201, 6),
 (203, 6),
 (204, 6),
 (205, 6),
 (207, 6),
 (208, 6),
 (210, 6),
 (211, 6),
 (212, 6),
 (218, 6),
 (220, 6),
 (221, 6),
 (222, 6),
 (223, 6),
 (225, 6),
 (234, 6),
 (235, 6),
 (236, 6),
 (237, 6),
 (240, 6),
 (242, 6),
 (243, 6),
 (246, 6),
 (249, 6),
 (250, 6),
 (256, 6),
 (258, 6),
 (260, 6),
 (261, 6),
 (262, 6),
 (266, 6),
 (270, 6),
 (271, 6),
 (273, 6),
 (274, 6),
 (278, 6),
 (281, 6),
 (282, 6),
 (311, 6),
 (312, 6),
 (315, 6),
 (320, 6),
 (321, 6),
 (324, 6),
 (325, 6),
 (328, 6),
 (329, 6),
 (332, 6),
 (334, 6),
 (335, 6),
 (342, 6),
 (350, 6),
 (358, 6),
 (361, 6),
 (365, 6),
 (367, 6),
 (368, 6),
 (371, 6),
 (375, 6),
 (376, 6),
 (378, 6),
 (379, 6),
 (384, 6),
 (396, 6),
 (397, 6),
 (399, 6),
 (400, 6),
 (401, 6),
 (402, 6),
 (406, 6),
 (409, 6),
 (413, 6),
 (414, 6),
 (416, 6),
 (417, 6),
 (418, 6),
 (419, 6),
 (429, 6),
 (431, 6),
 (432, 6),
 (433, 6),
 (435, 6),
 (437, 6),
 (444, 6),
 (445, 6),
 (446, 6),
 (448, 6),
 (449, 6),
 (451, 6),
 (454, 6),
 (456, 6),
 (460, 6),
 (463, 6),
 (464, 6),
 (466, 6),
 (468, 6),
 (480, 6),
 (481, 6),
 (484, 6),
 (488, 6),
 (490, 6),
 (496, 6),
 (500, 6),
 (504, 6),
 (514, 6),
 (524, 6),
 (525, 6),
 (526, 6),
 (527, 6),
 (528, 6),
 (535, 6),
 (536, 6),
 (537, 6),
 (541, 6),
 (547, 6),
 (549, 6),
 (550, 6),
 (554, 6),
 (555, 6),
 (556, 6),
 (557, 6),
 (558, 6),
 (559, 6),
 (564, 6),
 (573, 6),
 (575, 6),
 (576, 6),
 (577, 6),
 (578, 6),
 (581, 6),
 (582, 6),
 (589, 6),
 (591, 6),
 (594, 6),
 (595, 6),
 (596, 6),
 (600, 6),
 (605, 6),
 (606, 6),
 (608, 6),
 (614, 6),
 (615, 6),
 (616, 6),
 (617, 6),
 (618, 6),
 (619, 6),
 (623, 6),
 (624, 6),
 (625, 6),
 (628, 6),
 (630, 6),
 (632, 6),
 (636, 6),
 (639, 6),
 (640, 6),
 (643, 6),
 (646, 6),
 (647, 6),
 (654, 6),
 (656, 6),
 (657, 6),
 (658, 6),
 (659, 6),
 (660, 6),
 (663, 6),
 (664, 6),
 (665, 6),
 (667, 6),
 (668, 6),
 (669, 6),
 (670, 6),
 (677, 6),
 (680, 6),
 (684, 6),
 (685, 6),
 (687, 6),
 (693, 6),
 (698, 6),
 (699, 6),
 (700, 6),
 (7, 7),
 (8, 7),
 (9, 7),
 (11, 7),
 (12, 7),
 (13, 7),
 (14, 7),
 (15, 7),
 (18, 7),
 (19, 7),
 (20, 7),
 ...]