# Preprocessing of the Threatened Species State Lists

Publication date of the data: 28-08-2026

This dataset in available at https://data.gov.au/data/dataset/threatened-species-state-lists under the Creative Commons Attribution 3.0 Australia license.

The dataset contains:

1) 2,222 species, of which 700 are animals and 1,522 plants. Plants are left out in our database as we focus only on animals.

2) Per value the data cointains: scientific name, common name, threatened status, genus, species, subspecies, class, family, and a Yes/- column for each state or territory where it occurs.

In [16]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [17]:
load_dotenv()
password = os.getenv("DB_PASSWORD")
os.environ["DATABASE_URL"] = f"mysql+pymysql://root:{password}@localhost/animal_extinction_db"
engine = create_engine(os.environ["DATABASE_URL"])

In [ ]:
# Threatened Species State list (2026)
data = pd.read_csv("Data/Threatened_Species_State_Lists.csv", na_values=["-"])

In [19]:
print(list(data.columns))

['_id', 'Scientific Name', 'Common Name', 'Current Scientific Name', 'Threatened status', 'ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA', 'ACI', 'CKI', 'CI', 'CSI', 'JBT', 'NFI', 'HMI', 'AAT', 'CMA', 'Listed SPRAT TaxonID', 'Current SPRAT TaxonID', 'Kingdom', 'Class', 'Profile', 'Date extracted', 'NSL Name', 'Family', 'Genus', 'Species', 'Infraspecific Rank', 'Infraspecies', 'Species Author', 'Infraspecies Author']

In [20]:
# Filter only selected animal info

usedColumns = ['Scientific Name', 'Common Name', 'Threatened status', 
      'ACT', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA', 'ACI', 'CKI', 'CI', 'CSI', 'JBT', 'NFI', 'HMI', 'AAT', 'CMA', 
        'Kingdom', 'Class', 'Date extracted'] 

data = data[usedColumns]
data.head()

,Scientific Name,Common Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,...,CI,CSI,JBT,NFI,HMI,AAT,CMA,Kingdom,Class,Date extracted
0,Abutilon julianae,Norfolk Island Abutilon,Critically Endangered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Yes,NaN,NaN,NaN,Plantae,Magnoliopsida,2026-Aug-28
1,Acacia ammophila,NaN,Vulnerable,NaN,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Plantae,Magnoliopsida,2026-Aug-28
2,Acacia anomala,"Grass Wattle, Chittering Grass Wattle",Vulnerable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Plantae,Magnoliopsida,2026-Aug-28
3,Acacia aphylla,Leafless Rock Wattle,Vulnerable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Plantae,Magnoliopsida,2026-Aug-28
4,Acacia aprica,Blunt Wattle,Endangered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Plantae,Magnoliopsida,2026-Aug-28

In [21]:
# Filter out all species that are not animals
data = data[data['Kingdom'] != 'Plantae'].reset_index(drop=True)
data.head()

,Scientific Name,Common Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,...,CI,CSI,JBT,NFI,HMI,AAT,CMA,Kingdom,Class,Date extracted
0,Acanthiza iredalei rosinae,Slender-billed Thornbill (Gulf St Vincent),Vulnerable,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28
1,Acanthiza lineata whitei,Kangaroo Island Striated Thornbill,Vulnerable,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28
2,Acanthiza pusilla magnirostris,"King Island Brown Thornbill, Brown Thornbill (...",Endangered,NaN,NaN,NaN,NaN,NaN,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28
3,Acanthophis hawkei,Plains Death Adder,Vulnerable,NaN,NaN,Yes,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Reptilia,2026-Aug-28
4,Acanthornis magna greeniana,"King Island Scrubtit, Scrubtit (King Island)",Critically Endangered,NaN,NaN,NaN,NaN,NaN,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28

In [22]:
print(data['Threatened status'].unique())

<StringArray>
[            'Vulnerable',             'Endangered',  'Critically Endangered',
                'Extinct', 'Conservation Dependent',    'Extinct in the wild']
Length: 6, dtype: str

In [ ]:
# Converting the levels to the 2-letter abbreviations expected by the schema

level={"Least Concern":"LC","Near Threatened":"NT", "Vulnerable":"VU", "Endangered":"EN", "Critically Endangered":"CR", "Conservation Dependent":"CD", 
       "Extinct in the Wild":"EW", "Extinct":"EX", "Data Deficient":"DD", "Not Evaluated":"NE"}

data["Level"] = None

for index, row in data.iterrows():
    data.loc[index, "Level"] = level.get(row["Threatened status"], None)

data.head()

,Scientific Name,Common Name,Threatened status,ACT,NSW,NT,QLD,SA,TAS,VIC,...,CSI,JBT,NFI,HMI,AAT,CMA,Kingdom,Class,Date extracted,Level
0,Acanthiza iredalei rosinae,Slender-billed Thornbill (Gulf St Vincent),Vulnerable,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,VU
1,Acanthiza lineata whitei,Kangaroo Island Striated Thornbill,Vulnerable,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,VU
2,Acanthiza pusilla magnirostris,"King Island Brown Thornbill, Brown Thornbill (...",Endangered,NaN,NaN,NaN,NaN,NaN,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,EN
3,Acanthophis hawkei,Plains Death Adder,Vulnerable,NaN,NaN,Yes,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Reptilia,2026-Aug-28,VU
4,Acanthornis magna greeniana,"King Island Scrubtit, Scrubtit (King Island)",Critically Endangered,NaN,NaN,NaN,NaN,NaN,Yes,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,CR

In [24]:
data = data.drop(columns="Threatened status")

In [25]:
data["Year"] = None

for index, row in data.iterrows():
    data.loc[index, "Year"] = row["Date extracted"][0:4]

data.head()

,Scientific Name,Common Name,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,...,JBT,NFI,HMI,AAT,CMA,Kingdom,Class,Date extracted,Level,Year
0,Acanthiza iredalei rosinae,Slender-billed Thornbill (Gulf St Vincent),NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,VU,2026
1,Acanthiza lineata whitei,Kangaroo Island Striated Thornbill,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,VU,2026
2,Acanthiza pusilla magnirostris,"King Island Brown Thornbill, Brown Thornbill (...",NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,EN,2026
3,Acanthophis hawkei,Plains Death Adder,NaN,NaN,Yes,Yes,NaN,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,Animalia,Reptilia,2026-Aug-28,VU,2026
4,Acanthornis magna greeniana,"King Island Scrubtit, Scrubtit (King Island)",NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,2026-Aug-28,CR,2026

In [26]:
data = data.drop(columns="Date extracted")

In [27]:
for index, row in data.iterrows():
    name = str(row["Common Name"])
    name = name.split(",")[0]        # keep before the comma
    name = name.split("(")[0]        # keep before the bracket
    data.loc[index, "Common Name"] = name.strip()

data.head()

,Scientific Name,Common Name,ACT,NSW,NT,QLD,SA,TAS,VIC,WA,...,CSI,JBT,NFI,HMI,AAT,CMA,Kingdom,Class,Level,Year
0,Acanthiza iredalei rosinae,Slender-billed Thornbill,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,VU,2026
1,Acanthiza lineata whitei,Kangaroo Island Striated Thornbill,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,VU,2026
2,Acanthiza pusilla magnirostris,King Island Brown Thornbill,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,EN,2026
3,Acanthophis hawkei,Plains Death Adder,NaN,NaN,Yes,Yes,NaN,NaN,NaN,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Reptilia,VU,2026
4,Acanthornis magna greeniana,King Island Scrubtit,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Aves,CR,2026

In [ ]:
# Saving the preprocessing for later database insertion

data.to_csv("Data/Threatened_Species_State_Lists_cleaned.csv")